import Testing
import Foundation
@testable import iPocketTubeCore

// MARK: - CaptionsManager unit tests
//
// Tests verify the four key behaviours from task #63:
//   1. updateCaptionCue finds the active cue for a given time
//   2. updateCaptionCue returns nil when no cue spans the time
//   3. reset() clears all caption state and cancels any running fetch
//   4. selectCaption(nil) clears selection immediately

@Suite("CaptionsManager")
struct CaptionsManagerTests {

    // MARK: - 1. updateCaptionCue finds active cue

    @Test("updateCaptionCue returns cue whose window contains the given time")
    @MainActor func updateCaptionCueFindsMatch() async {
        let manager = CaptionsManager()
        manager.captionCues = [
            CaptionCue(startTime: 0.0, endTime: 2.0, text: "Hello"),
            CaptionCue(startTime: 3.0, endTime: 6.0, text: "World"),
            CaptionCue(startTime: 7.0, endTime: 10.0, text: "Goodbye"),
        ]
        manager.updateCaptionCue(for: 4.5)
        #expect(manager.currentCaptionCue?.text == "World")
    }

    // MARK: - 2. No cue outside windows

    @Test("updateCaptionCue returns nil when time is between cues")
    @MainActor func updateCaptionCueReturnsNilBetweenCues() async {
        let manager = CaptionsManager()
        manager.captionCues = [
            CaptionCue(startTime: 0.0, endTime: 2.0, text: "First"),
            CaptionCue(startTime: 5.0, endTime: 8.0, text: "Second"),
        ]
        manager.updateCaptionCue(for: 3.0)
        #expect(manager.currentCaptionCue == nil)
    }

    // MARK: - 3. reset() clears all state

    @Test("reset() clears availableCaptions, selectedCaption, cues, and cancels task")
    @MainActor func resetClearsAllState() async {
        let manager = CaptionsManager()
        let track = CaptionTrack(id: "en", baseURL: URL(string: "https://example.com")!,
                                  name: "English", languageCode: "en", isAutoGenerated: false)
        manager.availableCaptions = [track]
        manager.selectedCaption = track
        manager.currentCaptionCue = CaptionCue(startTime: 0, endTime: 1, text: "hi")
        manager.captionCues = [CaptionCue(startTime: 0, endTime: 1, text: "hi")]
        manager.captionFetchTask = Task { try? await Task.sleep(nanoseconds: 1_000_000_000) }

        manager.reset()

        #expect(manager.availableCaptions.isEmpty)
        #expect(manager.selectedCaption == nil)
        #expect(manager.currentCaptionCue == nil)
        #expect(manager.captionCues.isEmpty)
        #expect(manager.captionFetchTask == nil)
    }

    // MARK: - 4. selectCaption(nil) hides the overlay

    @Test("selectCaption(nil) hides overlay but preserves the loaded transcript")
    @MainActor func selectCaptionNilPreservesTranscript() async {
        let manager = CaptionsManager()
        let track = CaptionTrack(id: "fr", baseURL: URL(string: "https://example.com")!,
                                  name: "French", languageCode: "fr", isAutoGenerated: false)
        manager.selectedCaption = track
        manager.captionCues = [CaptionCue(startTime: 0, endTime: 2, text: "bonjour")]

        manager.selectCaption(nil)

        #expect(manager.selectedCaption == nil)
        #expect(manager.captionCues.map(\.text) == ["bonjour"])
        #expect(manager.captionFetchTask == nil)
    }

    // MARK: - 5. Empty cues returns nil

    @Test("updateCaptionCue returns nil when captionCues is empty")
    @MainActor func updateCaptionCueEmptyCues() async {
        let manager = CaptionsManager()
        manager.updateCaptionCue(for: 5.0)
        #expect(manager.currentCaptionCue == nil)
    }

    // MARK: - Task #131: autoApplyCaptionPreference matching logic

    /// Mirrors the matching logic in PlaybackViewModel.autoApplyCaptionPreference(tracks:).
    /// Tests cover exact match, BCP-47 prefix match, no match, and nil preference.
    private func autoApply(tracks: [CaptionTrack], preferred: String?) -> CaptionTrack? {
        CaptionsManager.preferredTrack(in: tracks, languageCode: preferred)
    }

    private func captionTrack(_ code: String) -> CaptionTrack {
        CaptionTrack(id: code, baseURL: URL(string: "https://example.com")!,
                     name: code, languageCode: code, isAutoGenerated: false)
    }

    @Test("autoApplyCaptionPreference exact match selects the right track")
    func captionAutoApply_exactMatch() {
        let tracks = [captionTrack("en"), captionTrack("es"), captionTrack("fr")]
        let result = autoApply(tracks: tracks, preferred: "es")
        #expect(result?.languageCode == "es", "Exact match must return the Spanish track")
    }

    @Test("autoApplyCaptionPreference prefix match selects locale variant")
    func captionAutoApply_prefixMatch() {
        let tracks = [captionTrack("en-US"), captionTrack("es")]
        let result = autoApply(tracks: tracks, preferred: "en")
        #expect(result?.languageCode == "en-US", "Prefix match 'en' must return 'en-US'")
    }

    @Test("autoApplyCaptionPreference no match returns nil")
    func captionAutoApply_noMatch_returnsNil() {
        let tracks = [captionTrack("fr"), captionTrack("de")]
        let result = autoApply(tracks: tracks, preferred: "ja")
        #expect(result == nil, "No match must return nil — captions stay off")
    }

    @Test("autoApplyCaptionPreference nil preference returns nil")
    func captionAutoApply_nilPreference_returnsNil() {
        let tracks = [captionTrack("en"), captionTrack("es")]
        let result = autoApply(tracks: tracks, preferred: nil)
        #expect(result == nil, "nil preference must leave captions off")
    }

    @Test("autoApplyCaptionPreference empty tracks returns nil")
    func captionAutoApply_emptyTracks_returnsNil() {
        let result = autoApply(tracks: [], preferred: "en")
        #expect(result == nil, "Empty track list must return nil without crashing")
    }

    @Test("Prepared audio applies resolved tracks only after playback has started")
    @MainActor func preparedAudioAppliesTracksAfterStart() {
        let manager = CaptionsManager { _ in [] }
        let identity = manager.beginPlaybackItem("video")
        var playbackStarted = false

        playbackStarted = true
        let applied = manager.applyAvailableCaptions(
            [captionTrack("en")],
            for: identity,
            preferredLanguage: nil
        )

        #expect(playbackStarted)
        #expect(applied)
        #expect(manager.availableCaptions.map(\.languageCode) == ["en"])
    }

    @Test("Caption cue loading is asynchronous and cannot gate playback start")
    @MainActor func cueLoadingDoesNotGatePlaybackStart() {
        let manager = CaptionsManager { _ in
            try await Task.sleep(for: .seconds(5))
            return []
        }
        let identity = manager.beginPlaybackItem("video")
        let playbackStarted = true

        let applied = manager.applyAvailableCaptions(
            [captionTrack("en")],
            for: identity,
            preferredLanguage: "en"
        )

        #expect(playbackStarted)
        #expect(applied)
        #expect(manager.selectedCaption?.languageCode == "en")
        #expect(manager.captionCues.isEmpty)
        #expect(manager.captionFetchTask != nil)
        manager.cancel()
    }

    @Test("Switching prepared audio items clears old cues immediately")
    @MainActor func itemSwitchClearsOldCues() {
        let manager = CaptionsManager()
        _ = manager.beginPlaybackItem("old")
        manager.captionCues = [CaptionCue(startTime: 0, endTime: 10, text: "old cue")]
        manager.updateCaptionCue(for: 1)

        let newIdentity = manager.beginPlaybackItem("new")

        #expect(newIdentity.itemID == "new")
        #expect(manager.availableCaptions.isEmpty)
        #expect(manager.captionCues.isEmpty)
        #expect(manager.currentCaptionCue == nil)
    }

    @Test("A stale metadata response cannot populate the new item")
    @MainActor func staleMetadataResponseIsIgnored() {
        let manager = CaptionsManager { _ in [] }
        let oldIdentity = manager.beginPlaybackItem("old")
        let newIdentity = manager.beginPlaybackItem("new")

        let staleApplied = manager.applyAvailableCaptions(
            [captionTrack("fr")],
            for: oldIdentity,
            preferredLanguage: "fr"
        )
        let currentApplied = manager.applyAvailableCaptions(
            [captionTrack("en")],
            for: newIdentity,
            preferredLanguage: nil
        )

        #expect(!staleApplied)
        #expect(currentApplied)
        #expect(manager.availableCaptions.map(\.languageCode) == ["en"])
    }

    @Test("No captions keeps overlay empty and line mode fallback nonempty")
    @MainActor func noCaptionsUsesSafeLineFallback() {
        let manager = CaptionsManager()
        let identity = manager.beginPlaybackItem("video")
        #expect(manager.applyAvailableCaptions([], for: identity, preferredLanguage: "en"))
        #expect(manager.currentCaptionCue == nil)

        let line = PlaybackLiveActivityPolicy.displayLine(
            transcriptLine: manager.currentCaptionCue?.text,
            title: "Title",
            author: "Author"
        )
        #expect(line == "Title")
        #expect(!line.isEmpty)
    }

    @Test("Synthetic current cue feeds line input while mode Off creates no presentation")
    @MainActor func currentCueFeedsLineButOffStaysOff() async {
        let manager = CaptionsManager { _ in
            [CaptionCue(startTime: 0, endTime: 10, text: "Тестовая реплика")]
        }
        let identity = manager.beginPlaybackItem("video")
        #expect(manager.applyAvailableCaptions(
            [captionTrack("ru")],
            for: identity,
            preferredLanguage: "ru",
            currentTime: 1
        ))
        await manager.captionFetchTask?.value
        manager.updateCaptionCue(for: 1)

        let line = PlaybackLiveActivityPolicy.displayLine(
            transcriptLine: manager.currentCaptionCue?.text,
            title: "Title",
            author: "Author"
        )
        #expect(line == "Тестовая реплика")
        #expect(PlaybackLiveActivityPolicy.presentation(
            for: .off,
            transcriptLine: line,
            duration: 60
        ) == nil)
    }

    @Test("Transcript cues are ordered, cleaned, and deduplicated")
    func transcriptOrderingAndDeduplication() {
        let normalized = CaptionTranscriptPolicy.normalizedCues([
            CaptionCue(startTime: 4, endTime: 6, text: "  Вторая   реплика "),
            CaptionCue(startTime: 1, endTime: 3, text: "Первая реплика"),
            CaptionCue(startTime: 1, endTime: 3, text: "Первая реплика"),
            CaptionCue(startTime: 8, endTime: 7, text: "Некорректная"),
        ])

        #expect(normalized.map(\.startTime) == [1, 4])
        #expect(normalized.map(\.text) == ["Первая реплика", "Вторая реплика"])
    }

    @Test("Active transcript cue follows actual playback time")
    func transcriptActiveCueSelection() {
        let cues = [
            CaptionCue(startTime: 0, endTime: 2, text: "Первая"),
            CaptionCue(startTime: 3, endTime: 5, text: "Вторая"),
        ]

        #expect(CaptionTranscriptPolicy.activeCueIndex(in: cues, at: 1) == 0)
        #expect(CaptionTranscriptPolicy.activeCueIndex(in: cues, at: 4) == 1)
        #expect(CaptionTranscriptPolicy.activeCueIndex(in: cues, at: 2.5) == nil)
    }

    @Test("Word-timed activation follows seek backward and forward without future text")
    @MainActor func wordTimedSeekSelection() {
        let manager = CaptionsManager()
        manager.captionCues = [
            CaptionCue(
                startTime: 0,
                endTime: 4,
                text: "Первая фраза",
                activationTime: 1.8
            ),
            CaptionCue(
                startTime: 2,
                endTime: 8,
                text: "Вторая фраза",
                activationTime: 4
            ),
        ]

        manager.updateCaptionCue(for: 1.5)
        #expect(manager.currentCaptionCue == nil)
        manager.updateCaptionCue(for: 2)
        #expect(manager.currentCaptionCue?.text == "Первая фраза")
        manager.updateCaptionCue(for: 5)
        #expect(manager.currentCaptionCue?.text == "Вторая фраза")
        manager.updateCaptionCue(for: 2)
        #expect(manager.currentCaptionCue?.text == "Первая фраза")
        #expect(CaptionTranscriptPolicy.seekTarget(for: manager.captionCues[1]) == 2)
    }

    @Test("Active cue observer cadence is responsive without a busy loop")
    func activeCueObserverCadence() {
        #expect(CaptionTranscriptPolicy.activeCueObserverInterval > 0)
        #expect(CaptionTranscriptPolicy.activeCueObserverInterval <= 0.2)
    }

    @Test("Transcript row seek uses the cue timestamp")
    func transcriptTapToSeek() {
        let cue = CaptionCue(startTime: 42.75, endTime: 45, text: "Реплика")
        #expect(CaptionTranscriptPolicy.seekTarget(for: cue) == 42.75)
        #expect(CaptionTranscriptPolicy.seekTarget(
            for: CaptionCue(startTime: -1, endTime: 2, text: "Реплика")
        ) == 0)
    }

    @Test("Transcript distinguishes loading, unavailable, and fetch failure")
    @MainActor func transcriptStateMapping() async {
        let emptyManager = CaptionsManager()
        let emptyIdentity = emptyManager.beginPlaybackItem("empty")
        #expect(emptyManager.transcriptState == .loading)
        #expect(emptyManager.applyAvailableCaptions(
            [],
            for: emptyIdentity,
            preferredLanguage: nil
        ))
        #expect(emptyManager.transcriptState == .unavailable)

        let failedManager = CaptionsManager { _ in throw URLError(.cannotLoadFromNetwork) }
        let failedIdentity = failedManager.beginPlaybackItem("failed")
        #expect(failedManager.applyAvailableCaptions(
            [captionTrack("ru")],
            for: failedIdentity,
            preferredLanguage: nil
        ))
        await failedManager.captionFetchTask?.value
        #expect(failedManager.transcriptState == .failed)
    }

    @Test("Automatic transcript and overlay reuse one captions fetch")
    @MainActor func transcriptDoesNotStartSecondFetch() async {
        let counter = CaptionLoaderCounter()
        let manager = CaptionsManager { _ in
            await counter.increment()
            return [CaptionCue(startTime: 0, endTime: 5, text: "Одна загрузка")]
        }
        let identity = manager.beginPlaybackItem("video")
        let track = captionTrack("ru")

        #expect(manager.applyAvailableCaptions(
            [track],
            for: identity,
            preferredLanguage: nil,
            currentTime: 1
        ))
        await manager.captionFetchTask?.value
        manager.selectCaption(track, currentTime: 1)
        _ = manager.applyAvailableCaptions(
            [track],
            for: identity,
            preferredLanguage: "ru",
            currentTime: 1
        )
        await manager.captionFetchTask?.value

        #expect(await counter.value == 1)
        #expect(manager.transcriptState == .ready)
        #expect(manager.currentCaptionCue?.text == "Одна загрузка")
    }
}

private actor CaptionLoaderCounter {
    private(set) var value = 0

    func increment() {
        value += 1
    }
}
