import Foundation
import Testing
@testable import iPocketTube
@testable import iPocketTubeCore

@Suite("Local transcript fallback")
struct LocalTranscriptTests {
    private let audioURL = URL(fileURLWithPath: "/tmp/already-owned-audio.m4a")

    @Test("YouTube captions have priority and never start a local job")
    @MainActor func youtubePriority() async {
        let counter = LocalTranscriptLoaderCounter()
        let manager = CaptionsManager(localTranscriptLoader: { _, _ in
            await counter.increment()
            return LocalTranscriptResult(cues: [], localeIdentifier: "ru-RU", wasCached: false)
        })
        let identity = manager.beginPlaybackItem("video")
        let track = CaptionTrack(
            id: "ru",
            baseURL: URL(string: "https://example.com/captions.vtt")!,
            name: "Русский",
            languageCode: "ru",
            isAutoGenerated: false
        )
        #expect(manager.applyAvailableCaptions([track], for: identity, preferredLanguage: nil))
        #expect(!manager.prepareLocalFallback(for: identity, eligibility: .allowed))
        #expect(!manager.startLocalTranscription(
            request: LocalTranscriptRequest(videoID: "video", audioURL: audioURL, localeIdentifier: "ru-RU"),
            for: identity
        ))
        #expect(await counter.value == 0)
        manager.cancel()
    }

    @Test("One item owns one local job and reuses the existing audio URL")
    @MainActor func oneJobNoDuplicateAudioFetch() async {
        let counter = LocalTranscriptLoaderCounter()
        let manager = CaptionsManager(localTranscriptLoader: { request, progress in
            await counter.record(url: request.audioURL)
            progress(.recognizing(0.5))
            try await Task.sleep(for: .milliseconds(30))
            return LocalTranscriptResult(
                cues: [CaptionCue(startTime: 0, endTime: 2, text: "Готово")],
                localeIdentifier: request.localeIdentifier,
                wasCached: false
            )
        })
        let identity = manager.beginPlaybackItem("video")
        #expect(manager.applyAvailableCaptions([], for: identity, preferredLanguage: nil))
        #expect(manager.prepareLocalFallback(for: identity, eligibility: .allowed))
        let request = LocalTranscriptRequest(
            videoID: "video",
            audioURL: audioURL,
            localeIdentifier: "ru-RU"
        )
        #expect(manager.startLocalTranscription(request: request, for: identity))
        #expect(!manager.startLocalTranscription(request: request, for: identity))
        await manager.localTranscriptionTask?.value
        #expect(await counter.value == 1)
        #expect(await counter.urls == [audioURL])
        #expect(manager.transcriptState == .ready)
    }

    @Test("A YouTube captions network error does not masquerade as absence")
    @MainActor func captionsNetworkErrorDoesNotStartLocalJob() async {
        let counter = LocalTranscriptLoaderCounter()
        let manager = CaptionsManager(
            cueLoader: { _ in throw URLError(.notConnectedToInternet) },
            localTranscriptLoader: { _, _ in
                await counter.increment()
                return LocalTranscriptResult(cues: [], localeIdentifier: "ru-RU", wasCached: false)
            }
        )
        let identity = manager.beginPlaybackItem("video")
        let track = CaptionTrack(
            id: "ru",
            baseURL: URL(string: "https://example.com/captions.vtt")!,
            name: "Русский",
            languageCode: "ru",
            isAutoGenerated: false
        )
        #expect(manager.applyAvailableCaptions([track], for: identity, preferredLanguage: nil))
        await manager.captionFetchTask?.value
        #expect(manager.transcriptState == .failed)
        #expect(manager.transcriptSource == .youtubeCaptions)
        #expect(await counter.value == 0)
    }

    @Test("Caption metadata failure remains an error and blocks local fallback")
    @MainActor func captionMetadataFailureBlocksLocalFallback() async {
        let counter = LocalTranscriptLoaderCounter()
        let manager = CaptionsManager(localTranscriptLoader: { _, _ in
            await counter.increment()
            return LocalTranscriptResult(cues: [], localeIdentifier: "ru-RU", wasCached: false)
        })
        let identity = manager.beginPlaybackItem("video")
        #expect(manager.failCaptionMetadata(for: identity))
        #expect(manager.transcriptState == .failed)
        #expect(manager.transcriptSource == .youtubeCaptions)
        #expect(!manager.prepareLocalFallback(for: identity, eligibility: .allowed))
        #expect(await counter.value == 0)
    }

    @Test("Switching items cancels the old local job and rejects its result")
    @MainActor func itemSwitchCancelsOldJob() async {
        let counter = LocalTranscriptLoaderCounter()
        let manager = CaptionsManager(localTranscriptLoader: { _, _ in
            await counter.increment()
            try await Task.sleep(for: .seconds(5))
            return LocalTranscriptResult(
                cues: [CaptionCue(startTime: 0, endTime: 2, text: "Старая реплика")],
                localeIdentifier: "ru-RU",
                wasCached: false
            )
        })
        let old = manager.beginPlaybackItem("old")
        #expect(manager.applyAvailableCaptions([], for: old, preferredLanguage: nil))
        #expect(manager.prepareLocalFallback(for: old, eligibility: .allowed))
        #expect(manager.startLocalTranscription(
            request: LocalTranscriptRequest(videoID: "old", audioURL: audioURL, localeIdentifier: "ru-RU"),
            for: old
        ))
        let new = manager.beginPlaybackItem("new")
        try? await Task.sleep(for: .milliseconds(20))
        #expect(manager.activePlaybackIdentity == new)
        #expect(manager.captionCues.isEmpty)
        #expect(manager.transcriptState == .loading)
    }

    @Test("Eligibility states are explicit and SpeechAnalyzer needs no permission")
    @MainActor func eligibilityAndPermissionMapping() {
        #expect(LocalTranscriptionPolicy.requiredPermission == .notRequired)
        let manager = CaptionsManager()
        let identity = manager.beginPlaybackItem("video")
        #expect(manager.applyAvailableCaptions([], for: identity, preferredLanguage: nil))

        #expect(manager.prepareLocalFallback(for: identity, eligibility: .disabled))
        #expect(manager.transcriptState == .localDisabled)
        #expect(manager.prepareLocalFallback(for: identity, eligibility: .lowPowerMode))
        #expect(manager.transcriptState == .localLowPowerMode)
        #expect(manager.prepareLocalFallback(for: identity, eligibility: .insufficientStorage))
        #expect(manager.transcriptState == .localInsufficientStorage)
    }

    @Test("Generated speech segments keep ordered timestamps and active cue behavior")
    func generatedCueTiming() {
        let cues = LocalSpeechCuePolicy.cues(from: [
            LocalSpeechSegment(startTime: 5, duration: 1, text: "вторая."),
            LocalSpeechSegment(startTime: 1, duration: 1, text: "Первая"),
            LocalSpeechSegment(startTime: 2.1, duration: 1, text: "реплика."),
            LocalSpeechSegment(startTime: 2.1, duration: 1, text: "реплика."),
        ])
        #expect(cues.map(\.startTime) == [1, 5])
        #expect(cues.map(\.text) == ["Первая реплика.", "вторая."])
        #expect(CaptionTranscriptPolicy.activeCueIndex(in: cues, at: 2.5) == 0)
        #expect(CaptionTranscriptPolicy.seekTarget(for: cues[1]) == 5)
    }

    @Test("Cache hit returns timed cues without another recognition")
    func cacheHit() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("axrtube-transcript-cache-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: directory) }
        let cache = LocalTranscriptCache(baseDirectory: directory)
        let cues = [CaptionCue(startTime: 1, endTime: 3, text: "Кэш")]
        try await cache.store(
            videoID: "video",
            localeIdentifier: "ru-RU",
            engine: .speechAnalyzer,
            cues: cues
        )

        let result = await cache.load(videoID: "video")
        let stagingURL = await cache.stagingURL(videoID: "video")

        #expect(result?.wasCached == true)
        #expect(result?.cues == cues)
        #expect(!FileManager.default.fileExists(atPath: stagingURL.path))
    }

    @Test("Retired automatic local generation setting defaults off and persists")
    func settingPersistence() throws {
        var settings = AppSettings()
        #expect(!settings.autoGenerateLocalTranscripts)
        settings.autoGenerateLocalTranscripts = true
        let decoded = try JSONDecoder().decode(
            AppSettings.self,
            from: JSONEncoder().encode(settings)
        )
        #expect(decoded.autoGenerateLocalTranscripts)
    }

    @Test("Full transcript formats copy and TXT payload with safe filename")
    func textExportFormatting() {
        let document = fixtureDocument(title: "Тест / ролик: * ?")
        #expect(document.safeBaseFilename == "Тест ролик")
        #expect(document.plainText.contains("[00:01] Первая реплика"))
        #expect(document.plainText.contains("[01:02] Вторая реплика"))
        #expect(document.plainText.contains("Источник: Перевод Apple на устройстве"))
        #expect(document.plainText.contains("watch?v=video-id"))
        #expect(String(data: Data(document.plainText.utf8), encoding: .utf8) == document.plainText)
    }

    @Test("PDF metadata contains public video identity and transcript source")
    func pdfMetadata() {
        let document = fixtureDocument(title: "Название ролика")
        #expect(document.pdfMetadata["Title"] == "Название ролика")
        #expect(document.pdfMetadata["Author"] == "AxrTube")
        #expect(document.pdfMetadata["Subject"]?.contains("video-id") == true)
        #expect(document.pdfMetadata["Subject"]?.contains("Перевод Apple на устройстве") == true)
    }

    private func fixtureDocument(title: String) -> TranscriptExportDocument {
        TranscriptExportDocument(
            title: title,
            videoID: "video-id",
            source: .appleTranslation,
            generatedAt: Date(timeIntervalSince1970: 0),
            cues: [
                CaptionCue(startTime: 1, endTime: 3, text: "Первая реплика"),
                CaptionCue(startTime: 62, endTime: 65, text: "Вторая реплика"),
            ]
        )
    }
}

private actor LocalTranscriptLoaderCounter {
    private(set) var value = 0
    private(set) var urls: [URL] = []

    func increment() { value += 1 }

    func record(url: URL) {
        value += 1
        urls.append(url)
    }
}
