import Foundation
import Testing
@testable import iPocketTube
@testable import iPocketTubeCore

@Suite("Russian transcript pipeline")
struct RussianTranscriptTests {
    private func track(_ language: String, automatic: Bool = false) -> CaptionTrack {
        CaptionTrack(
            id: "\(language)-\(automatic)",
            baseURL: URL(string: "https://example.com/\(language).vtt")!,
            name: language,
            languageCode: language,
            isAutoGenerated: automatic
        )
    }

    private func cues(language: String, count: Int = 48) -> [CaptionCue] {
        let englishSpeech = [
            "Kimi K3 just came out, and this is a historic launch for open-source AI models.",
            "The model is competitive across several coding and reasoning tasks that matter in daily work.",
            "In this walkthrough we will compare the results, explain the setup, and inspect the generated code.",
            "The important question is whether the workflow remains reliable when the project becomes more complex."
        ]
        let russianSpeech = [
            "Как вам кажется, что изменилось после событий, которые лично коснулись каждого участника разговора?",
            "Сегодня мы подробно обсудим причины решения, его последствия и планы на следующие несколько лет.",
            "Важно отделить личные впечатления от проверяемых фактов и спокойно выслушать разные точки зрения.",
            "В продолжении интервью собеседники отвечают на вопросы и приводят конкретные примеры из своей работы."
        ]
        return (0..<count).map { index in
            let text = language == "ru"
                ? russianSpeech[index % russianSpeech.count]
                : englishSpeech[index % englishSpeech.count]
            return CaptionCue(
                startTime: Double(index * 5),
                endTime: Double(index * 5) + 4.5,
                text: text
            )
        }
    }

    @Test("Deterministic EN and RU fixtures are spoken captions with known language and multi-minute coverage")
    func speechFixturePreflight() {
        let english = cues(language: "en")
        let russian = cues(language: "ru")
        #expect(english.count > 20)
        #expect(russian.count > 20)
        #expect((english.last?.endTime ?? 0) >= 180)
        #expect((russian.last?.endTime ?? 0) >= 180)
        #expect(RussianTranscriptPolicy.languageEvidence(in: english) == .english)
        #expect(RussianTranscriptPolicy.languageEvidence(in: russian) == .russian)
        #expect(english.allSatisfy { !$0.text.localizedCaseInsensitiveContains("music") })
        #expect(russian.allSatisfy { !$0.text.localizedCaseInsensitiveContains("музык") })
    }

    @Test("A manual Russian YouTube track wins over English and skips Translation")
    func russianTrackHasStrictPriority() {
        let selected = RussianTranscriptPolicy.preferredSourceTrack(in: [
            track("en"),
            track("ru", automatic: true),
            track("ru")
        ])
        #expect(selected?.languageCode == "ru")
        #expect(selected?.isAutoGenerated == false)
    }

    @Test("Strong Russian cues render immediately without a translation job")
    @MainActor func russianPassthrough() async {
        let counter = TranslationCallCounter()
        let russianCues = cues(language: "ru")
        let manager = CaptionsManager(
            cueLoader: { _ in russianCues },
            russianTranscriptLoader: { _, _ in
                await counter.increment()
                return RussianTranscriptResult(cues: [], wasCached: false)
            }
        )
        let identity = manager.beginPlaybackItem("ru-video")
        #expect(manager.applyAvailableCaptions(
            [track("en"), track("ru")],
            for: identity,
            preferredLanguage: "en"
        ))
        await manager.captionFetchTask?.value

        #expect(manager.selectedCaption?.languageCode == "ru")
        #expect(manager.captionCues == russianCues)
        #expect(manager.transcriptState == .ready)
        #expect(await counter.value == 0)
    }

    @Test("English cues stay private until the first Russian batch")
    @MainActor func englishNeverFlashes() async {
        let gate = TranslationGate()
        let englishCues = cues(language: "en")
        let translated = englishCues.enumerated().map { index, cue in
            CaptionCue(
                startTime: cue.startTime,
                endTime: cue.endTime,
                text: "Русская переведённая реплика номер \(index) с достаточным количеством текста."
            )
        }
        let manager = CaptionsManager(
            cueLoader: { _ in englishCues },
            russianTranscriptLoader: { _, progress in
                await gate.wait()
                progress(.translated(
                    cues: Array(translated.prefix(4)),
                    stage: .translatingCurrentFragment
                ))
                return RussianTranscriptResult(cues: translated, wasCached: false)
            }
        )
        let identity = manager.beginPlaybackItem("en-video")
        #expect(manager.applyAvailableCaptions(
            [track("en")],
            for: identity,
            preferredLanguage: "ru"
        ))
        await manager.captionFetchTask?.value

        #expect(manager.captionCues.isEmpty)
        #expect(manager.currentCaptionCue == nil)
        #expect(manager.transcriptState == .translationPreparing)

        await gate.release()
        for _ in 0..<50 where manager.transcriptState != .ready {
            try? await Task.sleep(for: .milliseconds(10))
        }
        #expect(manager.captionCues == translated)
        #expect(manager.transcriptState == .ready)
        #expect(manager.captionCues.allSatisfy { !$0.text.contains("English") })
    }

    @Test("Stale Russian preference cannot bypass strong English evidence")
    func stalePreferenceCannotBypassEnglish() {
        #expect(RussianTranscriptPolicy.resolvedSourceLanguage(
            cues: cues(language: "en", count: 30),
            trackLanguageCode: "ru"
        ) == .english)
    }

    @Test("Priority begins at playback, covers two-minute lookahead, then the rest")
    func playbackPriorityAndStableTimestamps() {
        let source = (0..<60).map { index in
            CaptionCue(
                startTime: Double(index * 5),
                endTime: Double(index * 5 + 4),
                text: "English \(index)"
            )
        }
        let order = RussianTranscriptPolicy.priorityOrder(
            cues: source,
            playbackTime: 100,
            pendingIndices: Set(source.indices)
        )
        #expect(order.first == 19)
        let lookaheadPrefix = order.prefix { source[$0].startTime <= 220 }
        #expect(lookaheadPrefix.contains(20))
        #expect(lookaheadPrefix.contains(44))

        let translated = RussianTranscriptPolicy.translatedCues(
            source: source,
            translationsByIndex: [20: "Русская реплика"]
        )
        #expect(translated.single?.startTime == source[20].startTime)
        #expect(translated.single?.endTime == source[20].endTime)
    }

    @Test("Translation preserves safe activation at the beginning, middle, and end")
    func translationPreservesWordTimedActivationWithoutDrift() {
        let source = [
            CaptionCue(startTime: 0, endTime: 4, text: "First", activationTime: 1.8),
            CaptionCue(startTime: 300, endTime: 304, text: "Middle", activationTime: 302.1),
            CaptionCue(startTime: 676, endTime: 681, text: "Last", activationTime: 678.56),
        ]
        let translated = RussianTranscriptPolicy.translatedCues(
            source: source,
            translationsByIndex: [0: "Начало", 1: "Середина", 2: "Конец"]
        )

        #expect(translated.map(\.startTime) == source.map(\.startTime))
        #expect(translated.map(\.endTime) == source.map(\.endTime))
        #expect(translated.map(\.activationTime) == source.map(\.activationTime))
    }

    @Test("Word-timed transcript invalidates the old cache identity")
    func wordTimedCacheMigration() {
        let legacy = [CaptionCue(startTime: 0, endTime: 4, text: "English phrase")]
        let wordTimed = [CaptionCue(
            startTime: 0,
            endTime: 4,
            text: "English phrase",
            activationTime: 3.6
        )]

        #expect(RussianTranscriptPolicy.cacheSchemaVersion == 3)
        #expect(RussianTranscriptPolicy.sourceHash(cues: legacy)
            != RussianTranscriptPolicy.sourceHash(cues: wordTimed))
    }

    @Test("Seek reprioritizes a live translation without exposing source cues")
    @MainActor func seekReprioritizes() async {
        let gate = TranslationGate()
        let priorities = PriorityRecorder()
        let englishCues = cues(language: "en", count: 80)
        let manager = CaptionsManager(
            cueLoader: { _ in englishCues },
            russianTranscriptLoader: { _, _ in
                await gate.wait()
                return RussianTranscriptResult(cues: [], wasCached: false)
            },
            russianTranscriptPriorityUpdater: { time in
                Task { await priorities.record(time) }
            }
        )
        let identity = manager.beginPlaybackItem("seek-video")
        #expect(manager.applyAvailableCaptions(
            [track("en")],
            for: identity,
            preferredLanguage: nil
        ))
        await manager.captionFetchTask?.value
        manager.updateCaptionCue(for: 125)
        try? await Task.sleep(for: .milliseconds(20))
        #expect(await priorities.values == [125])
        #expect(manager.captionCues.isEmpty)
        manager.cancel()
        await gate.release()
    }

    @Test("Offline preparation is retryable and never reveals English")
    @MainActor func retryablePreparationFailure() async {
        let englishCues = cues(language: "en")
        let manager = CaptionsManager(
            cueLoader: { _ in englishCues },
            russianTranscriptLoader: { _, _ in
                throw RussianTranscriptFailure.preparationDeclinedOrOffline
            }
        )
        let identity = manager.beginPlaybackItem("offline-video")
        #expect(manager.applyAvailableCaptions(
            [track("en")],
            for: identity,
            preferredLanguage: nil
        ))
        await manager.captionFetchTask?.value
        await manager.russianTranslationTask?.value
        #expect(manager.transcriptState == .translationRetryable)
        #expect(manager.captionCues.isEmpty)
    }

    @Test("Work queue resumes from cached indices and seek changes the next batch")
    func resumeAndSeekQueue() {
        let source = (0..<30).map { index in
            CaptionCue(
                startTime: Double(index * 5),
                endTime: Double(index * 5 + 4),
                text: "Cue \(index)"
            )
        }
        var queue = RussianTranscriptWorkQueue(
            cues: source,
            completedIndices: Set(0..<13),
            playbackTime: 0
        )
        queue.reprioritize(playbackTime: 100)
        let batch = queue.nextBatch(size: 3)
        #expect(batch == [19, 20, 21])
        #expect(batch.allSatisfy { $0 >= 13 })
    }

    @Test("Completed Russian cache reopens without another inference")
    func cacheRoundTrip() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("axrtube-russian-cache-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: directory) }
        let source = cues(language: "en")
        let request = RussianTranscriptRequest(
            videoID: "cache-video",
            sourceTrackID: "english-manual",
            sourceCues: source,
            sourceLanguageCode: "en",
            sourceHash: RussianTranscriptPolicy.sourceHash(cues: source),
            playbackTime: 0
        )
        let cache = RussianTranscriptCache(baseDirectory: directory)
        let translations = Dictionary(uniqueKeysWithValues: source.indices.map {
            ($0, "Русская кэшированная реплика \($0)")
        })
        try await cache.store(
            request: request,
            translationsByIndex: translations,
            completed: true,
            resumeCount: 0
        )
        let loaded = await cache.load(request: request)
        #expect(loaded?.completed == true)
        #expect(loaded?.translationsByIndex.count == source.count)
    }

    @Test("Streaming out-of-order responses map only through stable client identifiers")
    func streamingIdentifiers() {
        let videoID = "stream-video"
        let trackID = "track-en"
        let hash = "abc"
        let identifiers = Dictionary(uniqueKeysWithValues: [2, 5, 9].map { index in
            (RussianTranscriptPolicy.stableClientIdentifier(
                videoID: videoID,
                sourceTrackID: trackID,
                sourceHash: hash,
                cueIndex: index
            ), index)
        })
        let outOfOrder = [9, 2, 5].map {
            RussianTranscriptPolicy.stableClientIdentifier(
                videoID: videoID,
                sourceTrackID: trackID,
                sourceHash: hash,
                cueIndex: $0
            )
        }
        #expect(outOfOrder.compactMap {
            RussianTranscriptPolicy.responseIndex(
                clientIdentifier: $0,
                expectedIdentifiers: identifiers
            )
        } == [9, 2, 5])
        #expect(RussianTranscriptPolicy.responseIndex(
            clientIdentifier: "stale-request",
            expectedIdentifiers: identifiers
        ) == nil)
    }

    @Test("Atomic partial cache resumes after simulated suspension without repeating completed cues")
    func partialCacheResume() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("axrtube-russian-partial-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: directory) }
        let source = cues(language: "en", count: 40)
        let request = RussianTranscriptRequest(
            videoID: "background-video",
            sourceTrackID: "track-en",
            sourceCues: source,
            sourceLanguageCode: "en",
            sourceHash: RussianTranscriptPolicy.sourceHash(cues: source),
            playbackTime: 60
        )
        let cache = RussianTranscriptCache(baseDirectory: directory)
        let completed = Dictionary(uniqueKeysWithValues: (0..<13).map {
            ($0, "Русская реплика \($0)")
        })
        try await cache.store(
            request: request,
            translationsByIndex: completed,
            completed: false,
            resumeCount: 1
        )

        let loaded = try #require(await cache.load(request: request))
        var resumed = RussianTranscriptWorkQueue(
            cues: source,
            completedIndices: Set(loaded.translationsByIndex.keys),
            playbackTime: 60
        )
        let next = resumed.nextBatch()
        #expect(next.allSatisfy { $0 >= 13 })
        #expect(loaded.resumeCount == 1)
    }

    @Test("Cache identity separates exact caption tracks")
    func cacheSeparatesTracks() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("axrtube-russian-tracks-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: directory) }
        let source = cues(language: "en")
        let hash = RussianTranscriptPolicy.sourceHash(cues: source)
        let first = RussianTranscriptRequest(
            videoID: "same-video",
            sourceTrackID: "manual-en",
            sourceCues: source,
            sourceLanguageCode: "en",
            sourceHash: hash,
            playbackTime: 0
        )
        let second = RussianTranscriptRequest(
            videoID: "same-video",
            sourceTrackID: "auto-en",
            sourceCues: source,
            sourceLanguageCode: "en",
            sourceHash: hash,
            playbackTime: 0
        )
        let cache = RussianTranscriptCache(baseDirectory: directory)
        try await cache.store(
            request: first,
            translationsByIndex: [0: "Перевод"],
            completed: false,
            resumeCount: 0
        )
        #expect(await cache.load(request: first) != nil)
        #expect(await cache.load(request: second) == nil)
    }
}

private actor TranslationCallCounter {
    private(set) var value = 0
    func increment() { value += 1 }
}

private actor TranslationGate {
    private var isReleased = false
    private var continuation: CheckedContinuation<Void, Never>?

    func wait() async {
        if isReleased { return }
        await withCheckedContinuation { continuation in
            self.continuation = continuation
        }
    }

    func release() {
        isReleased = true
        continuation?.resume()
        continuation = nil
    }
}

private actor PriorityRecorder {
    private(set) var values: [TimeInterval] = []
    func record(_ value: TimeInterval) { values.append(value) }
}

private extension Array {
    var single: Element? { count == 1 ? first : nil }
}
