import Foundation
import PDFKit
import Testing
@testable import iPocketTube
@testable import iPocketTubeCore

@Suite("Transcript book")
struct TranscriptBookTests {
    private func metadata(videoID: String = "spoken-video") -> TranscriptBookMetadata {
        TranscriptBookMetadata(
            videoID: videoID,
            title: "Разговор о Swift *и* интерфейсах",
            channelTitle: "Канал [Разработка]",
            duration: 620
        )
    }

    private func cues(language: String, count: Int = 132) -> [CaptionCue] {
        let russian = [
            "Сегодня мы подробно обсуждаем архитектуру приложения и пользовательский сценарий.",
            "Сначала определим ограничения, затем проверим данные и только после этого сделаем вывод.",
            "Каждый участник разговора приводит конкретный пример из повседневной разработки.",
            "В конце раздела мы подводим итог и переходим к следующей практической теме.",
        ]
        let english = [
            "Today we discuss the application architecture and the complete user journey in detail.",
            "First we define the constraints, then verify the evidence, and only then reach a conclusion.",
            "Each speaker provides a concrete example from everyday software development work.",
            "At the end of the section we summarize the result and move to the next practical topic.",
        ]
        let source = language == "ru" ? russian : english
        return (0..<count).map { index in
            CaptionCue(
                startTime: Double(index * 5),
                endTime: Double(index * 5) + 4.5,
                text: source[index % source.count]
            )
        }
    }

    private func request(
        language: String = "ru",
        trackID: String = "ru-manual",
        force: Bool = false
    ) -> TranscriptBookRequest {
        TranscriptBookRequest(
            metadata: metadata(),
            captionTrackID: trackID,
            languageCode: language,
            cues: cues(language: language),
            forceRebuild: force
        )
    }

    private func track(_ language: String, automatic: Bool = false) -> CaptionTrack {
        CaptionTrack(
            id: "\(language)-\(automatic)",
            baseURL: URL(string: "https://example.com/\(language).vtt")!,
            name: language,
            languageCode: language,
            isAutoGenerated: automatic
        )
    }

    @Test("Russian track wins, while English remains the automatic fallback source")
    func trackPriority() {
        let tracks = TranscriptBookPolicy.preferredTracks(in: [
            track("en"),
            track("ru", automatic: true),
            track("ru"),
        ])
        #expect(tracks.first?.languageCode == "ru")
        #expect(tracks.first?.isAutoGenerated == false)
        #expect(tracks.contains { $0.languageCode == "en" })
    }

    @Test("Complete Russian and English tracks preserve first and last speech")
    func completeTracksPreserveEdges() throws {
        for language in ["ru", "en"] {
            let source = cues(language: language)
            let document = try TranscriptBookPolicy.makeDocument(request: TranscriptBookRequest(
                metadata: metadata(videoID: "\(language)-video"),
                captionTrackID: "\(language)-track",
                languageCode: language,
                cues: source
            ))
            #expect(document.sourceCueCount == source.count)
            #expect(document.searchableText.contains(source.first!.text))
            #expect(document.searchableText.contains(source.last!.text))
            #expect(document.duration >= 620)
            #expect(document.paragraphCount < source.count)
        }
    }

    @Test("YouTube roll-up repetition becomes one readable paragraph")
    func rollupDedupe() throws {
        let source = [
            CaptionCue(startTime: 0, endTime: 2, text: "Hello world"),
            CaptionCue(startTime: 2, endTime: 4, text: "Hello world again"),
            CaptionCue(startTime: 4, endTime: 6, text: "again today."),
        ]
        let document = try TranscriptBookPolicy.makeDocument(request: TranscriptBookRequest(
            metadata: metadata(),
            captionTrackID: "en-rollup",
            languageCode: "en",
            cues: source
        ))
        let text = document.sections.flatMap(\.paragraphs).map(\.text).joined(separator: " ")
        #expect(text == "Hello world again today.")
        #expect(text.components(separatedBy: "Hello world").count == 2)
    }

    @Test("Paragraphs and five-minute sections are compact and timestamped")
    func paragraphsAndSections() throws {
        let document = try TranscriptBookPolicy.makeDocument(request: request())
        #expect(document.sections.count >= 3)
        #expect(document.paragraphCount < document.sourceCueCount / 2)
        #expect(document.sections.first?.startTime == 0)
        #expect((document.sections.dropFirst().first?.startTime ?? 0) >= 300)
        #expect(document.markdown.contains("## Оглавление"))
        #expect(document.markdown.contains("<a id=\"section-"))
        #expect(document.markdown.contains("### [00:00]"))
    }

    @Test("Markdown is UTF-8, escaped, and includes portable metadata")
    func markdownUTF8AndEscaping() throws {
        let document = try TranscriptBookPolicy.makeDocument(request: request())
        let data = Data(document.markdown.utf8)
        let decoded = String(data: data, encoding: .utf8)
        #expect(decoded == document.markdown)
        #expect(document.markdown.contains("Разговор о Swift \\*и\\* интерфейсах"))
        #expect(document.markdown.contains("Канал \\[Разработка\\]"))
        #expect(document.markdown.contains("https://www.youtube.com/watch?v=spoken-video"))
        #expect(document.markdown.hasSuffix("\n"))
    }

    @Test("Adaptive HTML is self-contained, responsive, accessible, and UTF-8 safe")
    func adaptiveHTML() throws {
        let document = try TranscriptBookPolicy.makeDocument(request: request())
        let html = document.html
        #expect(String(data: Data(html.utf8), encoding: .utf8) == html)
        #expect(html.contains("<meta name=\"viewport\""))
        #expect(html.contains("color-scheme: light dark"))
        #expect(html.contains("@media (max-width: 620px)"))
        #expect(html.contains("prefers-reduced-transparency"))
        #expect(html.contains("prefers-contrast: more"))
        #expect(html.contains("Как проектировать") == false)
        #expect(html.contains("Разговор о Swift *и* интерфейсах"))
        #expect(html.contains("Канал [Разработка]"))
        #expect(!html.contains("<script"))
        #expect(!html.contains("src=\"http"))
    }

    @Test("Adaptive HTML escapes untrusted metadata and transcript text")
    func adaptiveHTMLEscaping() throws {
        let source = [CaptionCue(startTime: 0, endTime: 4, text: "Текст <b>не тег</b> & готов")] + cues(language: "ru", count: 24)
        let document = try TranscriptBookPolicy.makeDocument(request: TranscriptBookRequest(
            metadata: TranscriptBookMetadata(
                videoID: "html-escaping",
                title: "Заголовок <опасный>",
                channelTitle: "Автор & канал"
            ),
            captionTrackID: "ru-html",
            languageCode: "ru",
            cues: source
        ))
        #expect(document.html.contains("Заголовок &lt;опасный&gt;"))
        #expect(document.html.contains("Автор &amp; канал"))
        #expect(document.html.contains("&lt;b&gt;не тег&lt;/b&gt; &amp; готов"))
    }

    @Test("PDF has pages and extractable searchable Russian text")
    func searchablePDF() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptBookPDF-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let document = try TranscriptBookPolicy.makeDocument(request: request())
        let url = directory.appendingPathComponent("book.pdf")
        let pages = try TranscriptBookPDFRenderer().render(document: document, to: url)
        let pdf = try #require(PDFDocument(url: url))
        let extracted = pdf.string ?? ""
        #expect(pages > 1)
        #expect(pdf.pageCount == pages)
        #expect(extracted.contains("Разговор о Swift"))
        #expect(extracted.contains("Сегодня мы подробно обсуждаем"))
        #expect(extracted.contains("Исходное видео"))
    }

    @Test("Cache hit, identity invalidation, and atomic failed replacement")
    func cacheLifecycle() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptBookCache-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let service = TranscriptBookService(baseDirectory: directory)

        let first = try await service.prepare(request())
        let cached = try await service.prepare(request())
        #expect(!first.wasCached)
        #expect(cached.wasCached)
        #expect(first.document.cacheKey == cached.document.cacheKey)
        #expect(FileManager.default.fileExists(atPath: cached.artifacts.markdownURL.path))
        #expect(FileManager.default.fileExists(atPath: cached.artifacts.htmlURL.path))
        #expect(FileManager.default.fileExists(atPath: cached.artifacts.pdfURL.path))

        let changedTrack = try await service.prepare(request(trackID: "ru-revised"))
        #expect(!changedTrack.wasCached)
        #expect(changedTrack.document.cacheKey != first.document.cacheKey)

        let failing = TranscriptBookService(
            baseDirectory: directory,
            pdfRenderer: { _, _ in throw TranscriptBookFailure.exportFailed }
        )
        await #expect(throws: TranscriptBookFailure.self) {
            _ = try await failing.prepare(request(force: true))
        }
        let preserved = try await service.prepare(request())
        #expect(preserved.wasCached)
        #expect(preserved.document == first.document)
    }

    @Test("Every portable format produces a durable non-empty file payload")
    func portableFilePayloads() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("TranscriptBookPortable-\(UUID().uuidString)", isDirectory: true)
        let savedDirectory = directory.appendingPathComponent("Saved", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let service = TranscriptBookService(baseDirectory: directory.appendingPathComponent("Cache"))
        let result = try await service.prepare(request())
        try FileManager.default.createDirectory(at: savedDirectory, withIntermediateDirectories: true)

        for format in TranscriptBookFileFormat.allCases {
            let payload = try TranscriptBookFileExportPolicy.payload(
                from: result.artifacts,
                format: format
            )
            #expect(!payload.data.isEmpty)
            #expect(payload.filename.hasSuffix(".\(format.fileExtension)"))
            let savedURL = savedDirectory.appendingPathComponent(payload.filename)
            try payload.data.write(to: savedURL, options: .atomic)
            #expect(try Data(contentsOf: savedURL) == payload.data)
        }

        let cached = try await service.prepare(request())
        #expect(cached.wasCached)
        for format in TranscriptBookFileFormat.allCases {
            #expect(try !TranscriptBookFileExportPolicy.payload(
                from: cached.artifacts,
                format: format
            ).data.isEmpty)
        }
    }

    @Test("No captions is honest and does not create a document")
    func noCaptions() {
        #expect(throws: TranscriptBookFailure.noCaptions) {
            _ = try TranscriptBookPolicy.makeDocument(request: TranscriptBookRequest(
                metadata: metadata(),
                captionTrackID: "empty",
                languageCode: "ru",
                cues: []
            ))
        }
    }

    @Test("English production path stays hidden and exports one Russian canonical book")
    @MainActor func englishManagerPath() async throws {
        let translationCalls = BookCallCounter()
        let artifactRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent("BookManager-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: artifactRoot) }
        let english = cues(language: "en", count: 48)
        let russian = cues(language: "ru", count: 48)
        let service = TranscriptBookService(baseDirectory: artifactRoot)
        let manager = CaptionsManager(
            cueLoader: { _ in english },
            russianTranscriptLoader: { request, progress in
                await translationCalls.increment()
                #expect(request.sourceCues == english)
                progress(.translated(
                    cues: Array(russian.prefix(8)),
                    stage: .translatingCurrentFragment
                ))
                return RussianTranscriptResult(cues: russian, wasCached: false)
            },
            transcriptBookLoader: { request in
                try await service.prepare(request)
            }
        )
        let identity = manager.beginPlaybackItem(
            "en-video",
            bookMetadata: metadata(videoID: "en-video")
        )
        #expect(manager.applyAvailableCaptions(
            [track("en")],
            for: identity,
            preferredLanguage: "ru"
        ))
        await manager.captionFetchTask?.value
        #expect(manager.captionCues.allSatisfy { !$0.text.contains("Today we discuss") })
        await manager.russianTranslationTask?.value
        await manager.transcriptBookTask?.value
        let result = try #require(manager.transcriptBookResult)
        #expect(manager.transcriptBookState == .ready)
        #expect(result.document.languageCode == "ru")
        #expect(manager.transcriptSource == .appleTranslation)
        #expect(await translationCalls.value == 1)
        #expect(result.document.searchableText.contains("Сегодня мы подробно обсуждаем"))
        #expect(!result.document.searchableText.contains("Today we discuss"))
        #expect(result.document.markdown.contains("Сегодня мы подробно обсуждаем"))
        #expect(result.document.html.contains("Сегодня мы подробно обсуждаем"))
        let pdf = try #require(PDFDocument(url: result.artifacts.pdfURL))
        #expect(pdf.string?.contains("Сегодня мы подробно обсуждаем") == true)
        #expect(pdf.string?.contains("Today we discuss") == false)
    }

    @Test("Russian YouTube captions bypass Translation and build the same Russian formats")
    @MainActor func russianManagerPath() async throws {
        let translationCalls = BookCallCounter()
        let artifactRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent("BookManagerRU-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: artifactRoot) }
        let russian = cues(language: "ru", count: 48)
        let service = TranscriptBookService(baseDirectory: artifactRoot)
        let manager = CaptionsManager(
            cueLoader: { _ in russian },
            russianTranscriptLoader: { _, _ in
                await translationCalls.increment()
                throw RussianTranscriptFailure.translationFailed
            },
            transcriptBookLoader: { request in
                try await service.prepare(request)
            }
        )
        let identity = manager.beginPlaybackItem(
            "ru-video",
            bookMetadata: metadata(videoID: "ru-video")
        )
        #expect(manager.applyAvailableCaptions(
            [track("en"), track("ru")],
            for: identity,
            preferredLanguage: "en"
        ))
        await manager.captionFetchTask?.value
        await manager.transcriptBookTask?.value
        let result = try #require(manager.transcriptBookResult)
        #expect(manager.selectedCaption?.languageCode == "ru")
        #expect(manager.transcriptSource == .youtubeCaptions)
        #expect(result.document.languageCode == "ru")
        #expect(await translationCalls.value == 0)
        #expect(result.document.markdown.contains("Сегодня мы подробно обсуждаем"))
        #expect(result.document.html.contains("Сегодня мы подробно обсуждаем"))
    }
}

private actor BookCallCounter {
    private(set) var value = 0
    func increment() { value += 1 }
}
