import Foundation

// MARK: - CaptionsManager

public struct CaptionPlaybackIdentity: Equatable, Sendable {
    public let itemID: String
    public let generation: UInt64

    public init(itemID: String, generation: UInt64) {
        self.itemID = itemID
        self.generation = generation
    }
}

public enum CaptionTranscriptState: Equatable, Sendable {
    case loading
    case ready
    case translationPreparing
    case translationCurrentFragment
    case translationAhead
    case translationRemaining
    case translationRetryable
    case translationUnsupported
    case localPreparingAudio
    case localPreparingModel(progress: Double)
    case localGenerating(progress: Double)
    case localCancelled
    case localDisabled
    case localLowPowerMode
    case localInsufficientStorage
    case localPermissionDenied
    case localPermissionRestricted
    case localRecognitionUnavailable
    case unavailable
    case failed
}

public enum CaptionTranscriptPolicy {
    /// Five updates per second keep active-cue highlighting responsive without
    /// polling or installing a second playback clock.
    public static let activeCueObserverInterval: TimeInterval = 0.2

    public static func normalizedCues(_ cues: [CaptionCue]) -> [CaptionCue] {
        let sorted = cues
            .filter { $0.startTime.isFinite && $0.endTime.isFinite && $0.endTime > $0.startTime }
            .map { cue in
                CaptionCue(
                    startTime: max(0, cue.startTime),
                    endTime: max(0, cue.endTime),
                    text: cue.text
                        .split(whereSeparator: { $0.isWhitespace })
                        .joined(separator: " "),
                    activationTime: cue.activationTime.map {
                        min(
                            max(0, cue.endTime),
                            max(max(0, cue.startTime), $0)
                        )
                    }
                )
            }
            .filter { !$0.text.isEmpty }
            .sorted {
                if $0.startTime != $1.startTime { return $0.startTime < $1.startTime }
                if $0.endTime != $1.endTime { return $0.endTime < $1.endTime }
                return $0.text < $1.text
            }

        var seen = Set<CueKey>()
        return sorted.filter { cue in
            seen.insert(CueKey(cue)).inserted
        }
    }

    public static func activeCueIndex(in cues: [CaptionCue], at time: TimeInterval) -> Int? {
        guard time.isFinite else { return nil }
        return cues.lastIndex {
            $0.effectiveActivationTime <= time && $0.endTime > time
        }
    }

    public static func seekTarget(for cue: CaptionCue) -> TimeInterval {
        max(0, cue.startTime)
    }

    public static func automaticTrack(in tracks: [CaptionTrack]) -> CaptionTrack? {
        tracks.first(where: { !$0.isAutoGenerated }) ?? tracks.first
    }

    private struct CueKey: Hashable {
        let startMilliseconds: Int
        let endMilliseconds: Int
        let activationMilliseconds: Int?
        let text: String

        init(_ cue: CaptionCue) {
            startMilliseconds = Int((cue.startTime * 1_000).rounded())
            endMilliseconds = Int((cue.endTime * 1_000).rounded())
            activationMilliseconds = cue.activationTime.map {
                Int(($0 * 1_000).rounded())
            }
            text = cue.text
        }
    }
}

/// Owns caption state: `availableCaptions`, `selectedCaption`, `currentCaptionCue`,
/// `captionCues`, and `captionFetchTask`. Fully self-contained — no delegate needed.
@MainActor
@Observable
public final class CaptionsManager {

    public typealias CueLoader = @Sendable (URL) async throws -> [CaptionCue]
    public typealias LocalTranscriptLoader = @MainActor @Sendable (
        LocalTranscriptRequest,
        @escaping @Sendable (LocalTranscriptProgress) -> Void
    ) async throws -> LocalTranscriptResult
    public typealias RussianTranscriptLoader = @MainActor @Sendable (
        RussianTranscriptRequest,
        @escaping @Sendable (RussianTranscriptTranslationUpdate) -> Void
    ) async throws -> RussianTranscriptResult
    public typealias RussianTranscriptPriorityUpdater = @MainActor @Sendable (TimeInterval) -> Void
    public typealias TranscriptBookLoader = @MainActor @Sendable (
        TranscriptBookRequest
    ) async throws -> TranscriptBookResult

    // MARK: - State

    public var availableCaptions: [CaptionTrack] = []
    public var selectedCaption: CaptionTrack? = nil
    public var currentCaptionCue: CaptionCue? = nil
    public private(set) var transcriptState: CaptionTranscriptState = .loading
    public private(set) var transcriptSource: TranscriptSource?
    public private(set) var russianTranscriptTelemetry: RussianTranscriptTelemetry?
    public private(set) var localTranscriptEngine: LocalTranscriptionEngine?
    public var captionCues: [CaptionCue] = []
    public private(set) var transcriptBookState: TranscriptBookState = .collecting
    public private(set) var transcriptBookResult: TranscriptBookResult?

    // Not observed (task handle, not UI state)
    @ObservationIgnored public var captionFetchTask: Task<Void, Never>? = nil
    @ObservationIgnored public private(set) var localTranscriptionTask: Task<Void, Never>? = nil
    @ObservationIgnored public private(set) var russianTranslationTask: Task<Void, Never>? = nil
    @ObservationIgnored public private(set) var transcriptBookTask: Task<Void, Never>? = nil

    public private(set) var activePlaybackIdentity: CaptionPlaybackIdentity?

    private let cueLoader: CueLoader
    private let localTranscriptLoader: LocalTranscriptLoader?
    private let russianTranscriptLoader: RussianTranscriptLoader?
    private let russianTranscriptPriorityUpdater: RussianTranscriptPriorityUpdater?
    private let transcriptBookLoader: TranscriptBookLoader?
    private var playbackGeneration: UInt64 = 0
    private var selectionGeneration: UInt64 = 0
    private var localTranscriptionGeneration: UInt64 = 0
    private var russianTranslationGeneration: UInt64 = 0
    private var transcriptBookGeneration: UInt64 = 0
    private var loadedTrackID: String?
    private var sourceTrackLanguageCode = ""
    private var sourceCues: [CaptionCue] = []
    private var lastTranslationPriorityTime: TimeInterval = 0
    private var transcriptBookMetadata: TranscriptBookMetadata?

    // MARK: - Init

    public init(
        cueLoader: @escaping CueLoader = { url in
            try await WebVTTParser().fetchCues(from: url)
        },
        localTranscriptLoader: LocalTranscriptLoader? = nil,
        russianTranscriptLoader: RussianTranscriptLoader? = nil,
        russianTranscriptPriorityUpdater: RussianTranscriptPriorityUpdater? = nil,
        transcriptBookLoader: TranscriptBookLoader? = nil
    ) {
        self.cueLoader = cueLoader
        self.localTranscriptLoader = localTranscriptLoader
        self.russianTranscriptLoader = russianTranscriptLoader
        self.russianTranscriptPriorityUpdater = russianTranscriptPriorityUpdater
        self.transcriptBookLoader = transcriptBookLoader
    }

    // MARK: - Interface

    public func reset() {
        playbackGeneration &+= 1
        selectionGeneration &+= 1
        activePlaybackIdentity = nil
        clearCaptionState()
    }

    @discardableResult
    public func beginPlaybackItem(
        _ itemID: String,
        bookMetadata: TranscriptBookMetadata? = nil
    ) -> CaptionPlaybackIdentity {
        playbackGeneration &+= 1
        selectionGeneration &+= 1
        let identity = CaptionPlaybackIdentity(
            itemID: itemID,
            generation: playbackGeneration
        )
        activePlaybackIdentity = identity
        clearCaptionState()
        transcriptBookMetadata = bookMetadata ?? TranscriptBookMetadata(
            videoID: itemID,
            title: "Стенограмма",
            channelTitle: ""
        )
        transcriptState = .loading
        transcriptBookState = .collecting
        return identity
    }

    /// Restores a complete document without starting media playback or network work.
    @discardableResult
    public func restoreTranscript(_ result: TranscriptBookResult, for identity: CaptionPlaybackIdentity) -> Bool {
        guard activePlaybackIdentity == identity,
              result.document.metadata.videoID == identity.itemID else { return false }
        transcriptBookResult = result
        transcriptState = .ready
        transcriptBookState = .ready
        return true
    }

    @discardableResult
    public func applyAvailableCaptions(
        _ tracks: [CaptionTrack],
        for identity: CaptionPlaybackIdentity,
        preferredLanguage: String?,
        currentTime: TimeInterval = 0
    ) -> Bool {
        guard activePlaybackIdentity == identity else { return false }
        availableCaptions = tracks
        guard !tracks.isEmpty else {
            selectedCaption = nil
            transcriptSource = nil
            transcriptState = .unavailable
            transcriptBookState = .unavailable
            return true
        }
        localTranscriptionGeneration &+= 1
        localTranscriptionTask?.cancel()
        localTranscriptionTask = nil
        transcriptSource = .youtubeCaptions
        guard let transcriptTrack = TranscriptBookPolicy.preferredTrack(in: tracks) else {
            transcriptState = .unavailable
            transcriptBookState = .unavailable
            return true
        }
        // Prefer a real Russian YouTube track. English is kept as a private
        // source and translated by the single Apple Translation owner before
        // any cue or book artifact becomes visible to the user.
        selectedCaption = transcriptTrack
        sourceTrackLanguageCode = transcriptTrack.languageCode
        loadCuesIfNeeded(for: transcriptTrack, currentTime: currentTime)
        return true
    }

    @discardableResult
    public func failCaptionMetadata(for identity: CaptionPlaybackIdentity) -> Bool {
        guard activePlaybackIdentity == identity else { return false }
        russianTranslationGeneration &+= 1
        russianTranslationTask?.cancel()
        russianTranslationTask = nil
        availableCaptions = []
        selectedCaption = nil
        currentCaptionCue = nil
        captionCues = []
        transcriptSource = .youtubeCaptions
        transcriptState = .failed
        transcriptBookState = .failed
        transcriptBookResult = nil
        sourceCues = []
        return true
    }

    nonisolated public static func preferredTrack(
        in tracks: [CaptionTrack],
        languageCode: String?
    ) -> CaptionTrack? {
        guard let languageCode, !languageCode.isEmpty, !tracks.isEmpty else { return nil }
        let base = languageCode.components(separatedBy: "-").first ?? languageCode
        return tracks.first(where: { $0.languageCode == languageCode })
            ?? tracks.first(where: { $0.languageCode.hasPrefix(base) })
    }

    private func clearCaptionState() {
        localTranscriptionGeneration &+= 1
        russianTranslationGeneration &+= 1
        transcriptBookGeneration &+= 1
        availableCaptions = []
        selectedCaption = nil
        currentCaptionCue = nil
        captionCues = []
        transcriptSource = nil
        russianTranscriptTelemetry = nil
        transcriptBookResult = nil
        transcriptBookState = .collecting
        localTranscriptEngine = nil
        transcriptState = .loading
        loadedTrackID = nil
        sourceTrackLanguageCode = ""
        sourceCues = []
        transcriptBookMetadata = nil
        lastTranslationPriorityTime = 0
        captionFetchTask?.cancel()
        captionFetchTask = nil
        localTranscriptionTask?.cancel()
        localTranscriptionTask = nil
        russianTranslationTask?.cancel()
        russianTranslationTask = nil
        transcriptBookTask?.cancel()
        transcriptBookTask = nil
    }

    public func cancel() {
        selectionGeneration &+= 1
        localTranscriptionGeneration &+= 1
        russianTranslationGeneration &+= 1
        transcriptBookGeneration &+= 1
        captionFetchTask?.cancel()
        captionFetchTask = nil
        localTranscriptionTask?.cancel()
        localTranscriptionTask = nil
        russianTranslationTask?.cancel()
        russianTranslationTask = nil
        transcriptBookTask?.cancel()
        transcriptBookTask = nil
    }

    @discardableResult
    public func prepareLocalFallback(
        for identity: CaptionPlaybackIdentity,
        eligibility: LocalTranscriptionEligibility
    ) -> Bool {
        guard activePlaybackIdentity == identity, availableCaptions.isEmpty else { return false }
        guard !(transcriptState == .failed && transcriptSource == .youtubeCaptions) else {
            return false
        }
        if eligibility == .allowed, localTranscriptionTask != nil {
            return true
        }
        if eligibility == .allowed, transcriptSource == .localSpeech, transcriptState == .ready {
            return true
        }
        localTranscriptionGeneration &+= 1
        localTranscriptionTask?.cancel()
        localTranscriptionTask = nil
        captionCues = []
        currentCaptionCue = nil
        transcriptSource = .localSpeech
        switch eligibility {
        case .allowed:
            transcriptState = .localPreparingAudio
        case .disabled:
            transcriptState = .localDisabled
        case .lowPowerMode:
            transcriptState = .localLowPowerMode
        case .insufficientStorage:
            transcriptState = .localInsufficientStorage
        }
        return true
    }

    @discardableResult
    public func startLocalTranscription(
        request: LocalTranscriptRequest,
        for identity: CaptionPlaybackIdentity,
        currentTime: TimeInterval = 0
    ) -> Bool {
        guard activePlaybackIdentity == identity,
              identity.itemID == request.videoID,
              availableCaptions.isEmpty,
              transcriptState == .localPreparingAudio,
              localTranscriptionTask == nil,
              let localTranscriptLoader else { return false }

        transcriptSource = .localSpeech
        transcriptState = .localPreparingModel(progress: 0)
        let expectedIdentity = identity
        localTranscriptionGeneration &+= 1
        let expectedLocalGeneration = localTranscriptionGeneration
        localTranscriptionTask = Task { [weak self] in
            guard let self else { return }
            do {
                let result = try await localTranscriptLoader(request) { [weak self] progress in
                    Task { @MainActor [weak self] in
                        guard let self,
                              self.activePlaybackIdentity == expectedIdentity,
                              self.localTranscriptionGeneration == expectedLocalGeneration,
                              self.availableCaptions.isEmpty,
                              !Task.isCancelled else { return }
                        switch progress {
                        case .preparingModel(let value):
                            self.transcriptState = .localPreparingModel(
                                progress: min(1, max(0, value))
                            )
                        case .recognizing(let value):
                            self.transcriptState = .localGenerating(
                                progress: min(1, max(0, value))
                            )
                        }
                    }
                }
                guard !Task.isCancelled,
                      self.activePlaybackIdentity == expectedIdentity,
                      self.localTranscriptionGeneration == expectedLocalGeneration,
                      self.availableCaptions.isEmpty else { return }
                let cues = CaptionTranscriptPolicy.normalizedCues(result.cues)
                self.captionCues = cues
                self.transcriptSource = .localSpeech
                self.localTranscriptEngine = result.engine
                self.transcriptState = cues.isEmpty ? .unavailable : .ready
                self.updateCaptionCue(for: currentTime)
                self.localTranscriptionTask = nil
            } catch is CancellationError {
                guard self.activePlaybackIdentity == expectedIdentity,
                      self.localTranscriptionGeneration == expectedLocalGeneration else { return }
                self.captionCues = []
                self.currentCaptionCue = nil
                self.transcriptState = .localCancelled
                self.localTranscriptionTask = nil
            } catch let failure as LocalTranscriptFailure {
                guard self.activePlaybackIdentity == expectedIdentity,
                      self.localTranscriptionGeneration == expectedLocalGeneration else { return }
                self.captionCues = []
                self.currentCaptionCue = nil
                switch failure {
                case .permissionDenied:
                    self.transcriptState = .localPermissionDenied
                case .permissionRestricted:
                    self.transcriptState = .localPermissionRestricted
                case .onDeviceRecognitionUnavailable:
                    self.transcriptState = .localRecognitionUnavailable
                case .audioUnavailable:
                    self.transcriptState = .unavailable
                case .recognitionFailed:
                    self.transcriptState = .failed
                }
                self.localTranscriptionTask = nil
            } catch {
                guard self.activePlaybackIdentity == expectedIdentity,
                      self.localTranscriptionGeneration == expectedLocalGeneration else { return }
                self.captionCues = []
                self.currentCaptionCue = nil
                self.transcriptState = .failed
                self.localTranscriptionTask = nil
            }
        }
        return true
    }

    /// Selects the caption overlay track. Pass `nil` to hide the overlay while
    /// retaining the already loaded transcript owned by this manager.
    public func selectCaption(_ track: CaptionTrack?, currentTime: TimeInterval = 0) {
        selectedCaption = track
        guard let track else { return }
        sourceTrackLanguageCode = track.languageCode
        loadCuesIfNeeded(for: track, currentTime: currentTime)
    }

    private func loadCuesIfNeeded(for track: CaptionTrack, currentTime: TimeInterval) {
        if loadedTrackID == track.id {
            updateCaptionCue(for: currentTime)
            return
        }

        selectionGeneration &+= 1
        let expectedSelectionGeneration = selectionGeneration
        let expectedPlaybackIdentity = activePlaybackIdentity
        loadedTrackID = track.id
        currentCaptionCue = nil
        captionCues = []
        sourceCues = []
        transcriptState = .loading
        russianTranslationGeneration &+= 1
        russianTranslationTask?.cancel()
        russianTranslationTask = nil
        captionFetchTask?.cancel()
        captionFetchTask = nil
        let timeToApply = currentTime
        captionFetchTask = Task { [weak self] in
            guard let self else { return }
            do {
                let cues = CaptionTranscriptPolicy.normalizedCues(
                    try await self.cueLoader(track.baseURL)
                )
                guard !Task.isCancelled,
                      self.selectionGeneration == expectedSelectionGeneration,
                      self.activePlaybackIdentity == expectedPlaybackIdentity,
                      self.loadedTrackID == track.id else { return }
                self.applyLoadedSourceCues(
                    cues,
                    trackLanguageCode: track.languageCode,
                    currentTime: timeToApply,
                    playbackIdentity: expectedPlaybackIdentity,
                    selectionGeneration: expectedSelectionGeneration
                )
            } catch {
                guard !Task.isCancelled,
                      self.selectionGeneration == expectedSelectionGeneration,
                      self.activePlaybackIdentity == expectedPlaybackIdentity,
                      self.loadedTrackID == track.id else { return }
                self.captionCues = []
                self.sourceCues = []
                self.currentCaptionCue = nil
                self.transcriptState = .failed
                self.transcriptBookResult = nil
                self.transcriptBookState = .failed
            }
        }
    }

    private func applyLoadedSourceCues(
        _ cues: [CaptionCue],
        trackLanguageCode: String,
        currentTime: TimeInterval,
        playbackIdentity: CaptionPlaybackIdentity?,
        selectionGeneration: UInt64
    ) {
        guard !cues.isEmpty else {
            sourceCues = []
            captionCues = []
            transcriptState = .unavailable
            transcriptBookResult = nil
            transcriptBookState = .unavailable
            return
        }
        sourceCues = cues
        sourceTrackLanguageCode = trackLanguageCode
        let language = TranscriptBookPolicy.baseLanguage(trackLanguageCode)
        guard language == "ru" || language == "en" else {
            captionCues = []
            currentCaptionCue = nil
            transcriptState = .unavailable
            transcriptBookResult = nil
            transcriptBookState = .unavailable
            return
        }
        switch RussianTranscriptPolicy.resolvedSourceLanguage(
            cues: cues,
            trackLanguageCode: trackLanguageCode
        ) {
        case .russian:
            russianTranslationGeneration &+= 1
            russianTranslationTask?.cancel()
            russianTranslationTask = nil
            captionCues = cues
            transcriptSource = .youtubeCaptions
            transcriptState = .ready
            updateCaptionCue(for: currentTime)
            startTranscriptBookBuild(
                cues: cues,
                languageCode: "ru",
                playbackIdentity: playbackIdentity,
                expectedSelectionGeneration: selectionGeneration,
                forceRebuild: false
            )
        case .english:
            captionCues = []
            currentCaptionCue = nil
            transcriptBookResult = nil
            transcriptBookState = .collecting
            startRussianTranslation(
                currentTime: currentTime,
                playbackIdentity: playbackIdentity,
                expectedSelectionGeneration: selectionGeneration
            )
        case .ambiguous:
            captionCues = []
            currentCaptionCue = nil
            transcriptState = .unavailable
            transcriptBookResult = nil
            transcriptBookState = .unavailable
        }
    }

    public var availableTranscriptBookTracks: [CaptionTrack] {
        TranscriptBookPolicy.preferredTracks(in: availableCaptions)
    }

    public func selectTranscriptBookTrack(_ track: CaptionTrack) {
        guard availableTranscriptBookTracks.contains(where: { $0.id == track.id }) else { return }
        selectedCaption = track
        sourceTrackLanguageCode = track.languageCode
        loadCuesIfNeeded(for: track, currentTime: lastTranslationPriorityTime)
    }

    public func rebuildTranscriptBook() {
        guard let identity = activePlaybackIdentity else { return }
        let usesRussianTranslation = transcriptSource == .appleTranslation
            && !captionCues.isEmpty
        let bookCues = usesRussianTranslation ? captionCues : sourceCues
        guard !bookCues.isEmpty else { return }
        startTranscriptBookBuild(
            cues: bookCues,
            languageCode: usesRussianTranslation ? "ru" : sourceTrackLanguageCode,
            playbackIdentity: identity,
            expectedSelectionGeneration: selectionGeneration,
            forceRebuild: true
        )
    }

    private func startTranscriptBookBuild(
        cues: [CaptionCue],
        languageCode: String,
        playbackIdentity: CaptionPlaybackIdentity?,
        expectedSelectionGeneration: UInt64,
        forceRebuild: Bool
    ) {
        transcriptBookGeneration &+= 1
        transcriptBookTask?.cancel()
        transcriptBookTask = nil
        transcriptBookResult = nil
        transcriptBookState = .collecting
        guard let identity = playbackIdentity,
              activePlaybackIdentity == identity,
              let metadata = transcriptBookMetadata,
              let trackID = loadedTrackID ?? selectedCaption?.id,
              let transcriptBookLoader else {
            transcriptBookState = .failed
            return
        }
        let expectedBookGeneration = transcriptBookGeneration
        let request = TranscriptBookRequest(
            metadata: metadata,
            captionTrackID: trackID,
            languageCode: languageCode,
            cues: cues,
            forceRebuild: forceRebuild
        )
        transcriptBookTask = Task { [weak self] in
            guard let self else { return }
            do {
                let result = try await transcriptBookLoader(request)
                guard !Task.isCancelled,
                      self.activePlaybackIdentity == identity,
                      self.selectionGeneration == expectedSelectionGeneration,
                      self.transcriptBookGeneration == expectedBookGeneration else { return }
                self.transcriptBookResult = result
                self.transcriptBookState = .ready
                self.transcriptBookTask = nil
            } catch is CancellationError {
                guard self.activePlaybackIdentity == identity,
                      self.transcriptBookGeneration == expectedBookGeneration else { return }
                self.transcriptBookTask = nil
            } catch let failure as TranscriptBookFailure {
                guard self.activePlaybackIdentity == identity,
                      self.selectionGeneration == expectedSelectionGeneration,
                      self.transcriptBookGeneration == expectedBookGeneration else { return }
                self.transcriptBookResult = nil
                self.transcriptBookState = failure == .noCaptions ? .unavailable : .failed
                self.transcriptBookTask = nil
            } catch {
                guard self.activePlaybackIdentity == identity,
                      self.selectionGeneration == expectedSelectionGeneration,
                      self.transcriptBookGeneration == expectedBookGeneration else { return }
                self.transcriptBookResult = nil
                self.transcriptBookState = .failed
                self.transcriptBookTask = nil
            }
        }
    }

    private func startRussianTranslation(
        currentTime: TimeInterval,
        playbackIdentity: CaptionPlaybackIdentity?,
        expectedSelectionGeneration: UInt64
    ) {
        russianTranslationGeneration &+= 1
        russianTranslationTask?.cancel()
        russianTranslationTask = nil
        captionCues = []
        currentCaptionCue = nil
        transcriptBookResult = nil
        transcriptBookState = .collecting
        lastTranslationPriorityTime = currentTime

        guard let identity = playbackIdentity,
              activePlaybackIdentity == identity,
              let russianTranscriptLoader else {
            transcriptState = .translationUnsupported
            transcriptBookState = .failed
            return
        }

        transcriptSource = .appleTranslation
        transcriptState = .translationPreparing
        let expectedTranslationGeneration = russianTranslationGeneration
        let request = RussianTranscriptRequest(
            videoID: identity.itemID,
            sourceTrackID: loadedTrackID ?? selectedCaption?.id ?? "unknown-track",
            sourceCues: sourceCues,
            sourceLanguageCode: "en",
            sourceHash: RussianTranscriptPolicy.sourceHash(cues: sourceCues),
            playbackTime: currentTime
        )
        russianTranslationTask = Task { [weak self] in
            guard let self else { return }
            do {
                let result = try await russianTranscriptLoader(request) { [weak self] update in
                    Task { @MainActor [weak self] in
                        guard let self,
                              !Task.isCancelled,
                              self.activePlaybackIdentity == identity,
                              self.selectionGeneration == expectedSelectionGeneration,
                              self.russianTranslationGeneration == expectedTranslationGeneration else { return }
                        self.applyRussianTranslationUpdate(update, currentTime: self.lastTranslationPriorityTime)
                    }
                }
                guard !Task.isCancelled,
                      self.activePlaybackIdentity == identity,
                      self.selectionGeneration == expectedSelectionGeneration,
                      self.russianTranslationGeneration == expectedTranslationGeneration else { return }
                // A progress callback may already be queued on MainActor. Invalidate
                // it before publishing the terminal result so a late partial batch
                // can never replace the completed Russian transcript.
                self.russianTranslationGeneration &+= 1
                guard RussianTranscriptPolicy.languageEvidence(in: result.cues) != .english else {
                    self.captionCues = []
                    self.currentCaptionCue = nil
                    self.transcriptState = .failed
                    self.russianTranslationTask = nil
                    return
                }
                self.captionCues = result.cues
                self.transcriptSource = .appleTranslation
                self.transcriptState = result.cues.isEmpty ? .unavailable : .ready
                self.updateCaptionCue(for: self.lastTranslationPriorityTime)
                self.russianTranslationTask = nil
                if result.cues.isEmpty {
                    self.transcriptBookState = .unavailable
                } else {
                    self.startTranscriptBookBuild(
                        cues: result.cues,
                        languageCode: "ru",
                        playbackIdentity: identity,
                        expectedSelectionGeneration: expectedSelectionGeneration,
                        forceRebuild: false
                    )
                }
            } catch is CancellationError {
                guard self.activePlaybackIdentity == identity,
                      self.russianTranslationGeneration == expectedTranslationGeneration else { return }
                self.russianTranslationGeneration &+= 1
                self.russianTranslationTask = nil
            } catch let failure as RussianTranscriptFailure {
                guard self.activePlaybackIdentity == identity,
                      self.russianTranslationGeneration == expectedTranslationGeneration else { return }
                self.russianTranslationGeneration &+= 1
                self.captionCues = []
                self.currentCaptionCue = nil
                self.transcriptState = switch failure {
                case .preparationDeclinedOrOffline: .translationRetryable
                case .unsupportedLanguagePair: .translationUnsupported
                case .translationFailed: .failed
                }
                self.transcriptBookState = .failed
                self.russianTranslationTask = nil
            } catch {
                guard self.activePlaybackIdentity == identity,
                      self.russianTranslationGeneration == expectedTranslationGeneration else { return }
                self.russianTranslationGeneration &+= 1
                self.captionCues = []
                self.currentCaptionCue = nil
                self.transcriptState = .failed
                self.transcriptBookState = .failed
                self.russianTranslationTask = nil
            }
        }
    }

    private func applyRussianTranslationUpdate(
        _ update: RussianTranscriptTranslationUpdate,
        currentTime: TimeInterval
    ) {
        switch update {
        case .stage(let stage):
            transcriptState = transcriptState(for: stage)
        case .translated(let cues, let stage):
            guard RussianTranscriptPolicy.languageEvidence(in: cues) != .english else { return }
            captionCues = CaptionTranscriptPolicy.normalizedCues(cues)
            transcriptSource = .appleTranslation
            transcriptState = transcriptState(for: stage)
            updateCaptionCue(for: currentTime)
        case .telemetry(let telemetry):
            russianTranscriptTelemetry = telemetry
        }
    }

    private func transcriptState(
        for stage: RussianTranscriptTranslationStage
    ) -> CaptionTranscriptState {
        switch stage {
        case .preparingAssets: .translationPreparing
        case .translatingCurrentFragment: .translationCurrentFragment
        case .translatingAhead: .translationAhead
        case .translatingRemaining: .translationRemaining
        }
    }

    public func retryRussianTranslation() {
        guard !sourceCues.isEmpty,
              let identity = activePlaybackIdentity else { return }
        startRussianTranslation(
            currentTime: lastTranslationPriorityTime,
            playbackIdentity: identity,
            expectedSelectionGeneration: selectionGeneration
        )
    }

    /// Updates `currentCaptionCue` for the given playback position.
    public func updateCaptionCue(for time: TimeInterval) {
        if isTranslationActive,
           time.isFinite,
           abs(time - lastTranslationPriorityTime) >= 0.75 {
            lastTranslationPriorityTime = max(0, time)
            russianTranscriptPriorityUpdater?(lastTranslationPriorityTime)
        }
        guard let index = CaptionTranscriptPolicy.activeCueIndex(in: captionCues, at: time) else {
            currentCaptionCue = nil
            return
        }
        currentCaptionCue = captionCues[index]
    }

    private var isTranslationActive: Bool {
        switch transcriptState {
        case .translationPreparing, .translationCurrentFragment, .translationAhead,
             .translationRemaining:
            true
        default:
            false
        }
    }
}
