import Foundation

// MARK: - CaptionTrack

/// A single caption track as returned by YouTube's /player InnerTube endpoint.
/// Each track provides a WebVTT file at `baseURL` containing time-coded text cues.
public struct CaptionTrack: Identifiable, Hashable, Sendable {
    public let id: String               // vssId, e.g. ".en" or "a.en"
    public let baseURL: URL
    public let name: String             // Localised display name, e.g. "English"
    public let languageCode: String     // ISO 639-1, e.g. "en"
    public let isAutoGenerated: Bool    // true when vssId starts with "a." or kind == "asr"

    public init(
        id: String,
        baseURL: URL,
        name: String,
        languageCode: String,
        isAutoGenerated: Bool
    ) {
        self.id = id
        self.baseURL = baseURL
        self.name = name
        self.languageCode = languageCode
        self.isAutoGenerated = isAutoGenerated
    }
}

// MARK: - CaptionCue

/// A single timed text segment parsed from a WebVTT file.
public struct CaptionCue: Codable, Equatable, Hashable, Sendable {
    public let startTime: TimeInterval
    public let endTime: TimeInterval
    public let text: String
    /// Earliest playback time at which the complete cue text is safe to present.
    /// YouTube ASR roll-up cues can contain words whose inline timestamps are
    /// later than the cue's nominal start. Keeping this separate preserves the
    /// original timestamp for seeking while preventing future text from being
    /// highlighted before it is spoken.
    public let activationTime: TimeInterval?

    public init(
        startTime: TimeInterval,
        endTime: TimeInterval,
        text: String,
        activationTime: TimeInterval? = nil
    ) {
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
        self.activationTime = activationTime
    }

    public var effectiveActivationTime: TimeInterval {
        activationTime ?? startTime
    }
}

// MARK: - WebVTTParser

/// Downloads and parses a WebVTT subtitle track.
/// Designed as an `actor` so concurrent fetches are safe.
public actor WebVTTParser {
    private let session: URLSession

    public init(session: URLSession = .shared) {
        self.session = session
    }

    /// Fetches and parses the VTT file at `url`. Returns cues sorted by start time.
    public func fetchCues(from url: URL) async throws -> [CaptionCue] {
        var request = URLRequest(url: url)
        request.setValue("text/vtt, */*", forHTTPHeaderField: "Accept")
        let (data, response) = try await session.data(for: request)
        if let response = response as? HTTPURLResponse,
           !(200...299).contains(response.statusCode) {
            throw URLError(.badServerResponse)
        }
        guard let text = String(data: data, encoding: .utf8) else {
            throw URLError(.cannotDecodeContentData)
        }
        return parseVTT(text)
    }

    // MARK: - VTT parsing

    /// Parses a WebVTT string into `CaptionCue` values.
    /// Handles:
    ///   - WEBVTT header / NOTE / STYLE blocks
    ///   - Optional cue identifier lines
    ///   - Timestamp lines: "HH:MM:SS.mmm --> HH:MM:SS.mmm [settings]"
    ///   - Multi-line cue text
    ///   - `<...>` inline tags (stripped) and common HTML entities (decoded)
    nonisolated public func parseVTT(_ text: String) -> [CaptionCue] {
        struct ParsedCue {
            let startTime: TimeInterval
            let endTime: TimeInterval
            let payloadLines: [String]
            let inlineTimestamps: [TimeInterval]
        }

        var parsedCues: [ParsedCue] = []
        let lines = text.components(separatedBy: .newlines)
        var i = 0

        // Skip the mandatory WEBVTT header line and any initial metadata
        while i < lines.count, !lines[i].contains("-->") { i += 1 }

        while i < lines.count {
            let line = lines[i].trimmingCharacters(in: .whitespaces)

            // Blank line → separator between cue blocks; advance
            if line.isEmpty { i += 1; continue }

            // If this line looks like a cue identifier (no "-->"), skip it
            if !line.contains("-->") { i += 1; continue }

            // Timestamp line: "00:00:01.000 --> 00:00:03.000 align:start size:95%"
            let arrowParts = line.components(separatedBy: " --> ")
            guard arrowParts.count >= 2,
                  let start = parseVTTTimestamp(arrowParts[0].trimmingCharacters(in: .whitespaces)),
                  let end = parseVTTTimestamp(
                    arrowParts[1]
                        .components(separatedBy: " ")
                        .first ?? ""
                  )
            else { i += 1; continue }

            i += 1

            // YouTube ASR occasionally inserts a whitespace-only service line
            // between the timestamp and the first real payload line. Ignore only
            // leading blanks; a blank after payload still terminates the cue.
            var textLines: [String] = []
            var foundPayload = false
            while i < lines.count {
                let tl = lines[i].trimmingCharacters(in: .whitespaces)
                if tl.contains("-->") { break }
                if tl.isEmpty {
                    i += 1
                    if foundPayload { break }
                    continue
                }
                textLines.append(tl)
                foundPayload = true
                i += 1
            }

            let inlineTimestamps = textLines.flatMap(inlineTimestamps(in:))
            parsedCues.append(ParsedCue(
                startTime: start,
                endTime: end,
                payloadLines: textLines,
                inlineTimestamps: inlineTimestamps
            ))
        }

        let hasWordTimedRollup = parsedCues.contains { !$0.inlineTimestamps.isEmpty }
        var cues = parsedCues.flatMap { parsed -> [CaptionCue] in
            guard parsed.endTime > parsed.startTime else { return [] }

            // YouTube ASR alternates useful word-timed cues with 10 ms roll-up
            // snapshots. The snapshots repeat the previous text and should never
            // become separate rows or translation requests.
            if hasWordTimedRollup,
               parsed.inlineTimestamps.isEmpty,
               parsed.endTime - parsed.startTime <= 0.05 {
                return []
            }

            let sourceLines: [String]
            if !parsed.inlineTimestamps.isEmpty, let tail = parsed.payloadLines.last {
                // Earlier lines are the already-present roll-up prefix. Only the
                // final line contains the newly spoken words.
                sourceLines = [tail]
            } else {
                sourceLines = parsed.payloadLines
            }
            let raw = sourceLines.joined(separator: "\n")
            if !parsed.inlineTimestamps.isEmpty {
                return wordTimedCues(
                    from: raw,
                    cueStart: parsed.startTime,
                    cueEnd: parsed.endTime
                )
            }
            let cleaned = stripVTTTags(raw).decodingHTMLEntities()
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !cleaned.isEmpty else { return [] }
            return [CaptionCue(
                startTime: parsed.startTime,
                endTime: parsed.endTime,
                text: cleaned
            )]
        }
        .sorted { $0.startTime < $1.startTime }

        if hasWordTimedRollup {
            // The active window changes only when the next small word group is
            // safe to reveal. This removes overlaps and gaps without a timer.
            for index in cues.indices.dropLast() {
                let nextActivation = cues[index + 1].effectiveActivationTime
                let safeEnd = max(cues[index].effectiveActivationTime + 0.01, nextActivation)
                cues[index] = CaptionCue(
                    startTime: cues[index].startTime,
                    endTime: safeEnd,
                    text: cues[index].text,
                    activationTime: cues[index].activationTime
                )
            }
        }
        return cues
    }

    // MARK: - Timestamp parsing

    /// Parses a VTT timestamp "HH:MM:SS.mmm" or "MM:SS.mmm" into seconds.
    nonisolated private func parseVTTTimestamp(_ s: String) -> TimeInterval? {
        let parts = s.components(separatedBy: ":")
        switch parts.count {
        case 2:
            guard let m = Double(parts[0]), let sec = Double(parts[1]) else { return nil }
            return m * 60 + sec
        case 3:
            guard let h = Double(parts[0]),
                  let m = Double(parts[1]),
                  let sec = Double(parts[2]) else { return nil }
            return h * 3600 + m * 60 + sec
        default:
            return nil
        }
    }

    nonisolated private func inlineTimestamps(in text: String) -> [TimeInterval] {
        let pattern = #"<(\d{2}:\d{2}:\d{2}\.\d+)>"#
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        return regex.matches(in: text, range: range).compactMap { match in
            guard let valueRange = Range(match.range(at: 1), in: text) else { return nil }
            return parseVTTTimestamp(String(text[valueRange]))
        }
    }

    nonisolated private func wordTimedCues(
        from rawText: String,
        cueStart: TimeInterval,
        cueEnd: TimeInterval
    ) -> [CaptionCue] {
        struct Token {
            let startTime: TimeInterval
            let text: String
        }

        let pattern = #"<(\d{2}:\d{2}:\d{2}\.\d+)>"#
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
        let fullRange = NSRange(rawText.startIndex..<rawText.endIndex, in: rawText)
        let matches = regex.matches(in: rawText, range: fullRange)
        guard !matches.isEmpty else { return [] }

        var tokens: [Token] = []
        func appendToken(raw: String, time: TimeInterval) {
            let cleaned = stripVTTTags(raw).decodingHTMLEntities()
                .split(whereSeparator: { $0.isWhitespace })
                .joined(separator: " ")
            guard !cleaned.isEmpty else { return }
            tokens.append(Token(
                startTime: min(cueEnd, max(cueStart, time)),
                text: cleaned
            ))
        }
        var segmentStart = rawText.startIndex
        var segmentTime = cueStart
        for match in matches {
            guard let markerRange = Range(match.range, in: rawText),
                  let valueRange = Range(match.range(at: 1), in: rawText) else { continue }
            appendToken(
                raw: String(rawText[segmentStart..<markerRange.lowerBound]),
                time: segmentTime
            )
            if let parsedTime = parseVTTTimestamp(String(rawText[valueRange])) {
                segmentTime = parsedTime
            }
            segmentStart = markerRange.upperBound
        }
        appendToken(
            raw: String(rawText[segmentStart...]),
            time: segmentTime
        )
        guard !tokens.isEmpty else { return [] }

        // Keep translation requests phrase-like but short enough for honest
        // playback sync. A group spans at most 0.75 s of source word starts.
        let maximumGroupSpan: TimeInterval = 0.75
        let allowedEarlyPresentation: TimeInterval = 0.2
        var groups: [[Token]] = []
        var group: [Token] = []
        for token in tokens {
            if let first = group.first,
               token.startTime - first.startTime > maximumGroupSpan {
                groups.append(group)
                group = []
            }
            group.append(token)
        }
        if !group.isEmpty { groups.append(group) }

        return groups.compactMap { group in
            guard let first = group.first, let last = group.last else { return nil }
            let text = group.map(\.text)
                .joined(separator: " ")
                .split(whereSeparator: { $0.isWhitespace })
                .joined(separator: " ")
            guard !text.isEmpty else { return nil }
            let activation = min(
                max(first.startTime, cueEnd - 0.01),
                max(first.startTime, last.startTime - allowedEarlyPresentation)
            )
            return CaptionCue(
                startTime: first.startTime,
                endTime: cueEnd,
                text: text,
                activationTime: activation
            )
        }
    }


    // MARK: - Tag stripping

    /// Removes VTT inline tags: `<00:00:01.234>`, `<c.yellow>`, `<b>`, `</b>`, etc.
    nonisolated private func stripVTTTags(_ s: String) -> String {
        var result = ""
        result.reserveCapacity(s.count)
        var inTag = false
        for ch in s {
            if ch == "<" { inTag = true }
            else if ch == ">" { inTag = false }
            else if !inTag { result.append(ch) }
        }
        return result
    }
}

// MARK: - HTML entity decoding

private extension String {
    func decodingHTMLEntities() -> String {
        self
            .replacingOccurrences(of: "&amp;", with: "&")
            .replacingOccurrences(of: "&lt;", with: "<")
            .replacingOccurrences(of: "&gt;", with: ">")
            .replacingOccurrences(of: "&quot;", with: "\"")
            .replacingOccurrences(of: "&#39;", with: "'")
            .replacingOccurrences(of: "&nbsp;", with: " ")
            .replacingOccurrences(of: "&#x27;", with: "'")
            .replacingOccurrences(of: "&#x2F;", with: "/")
    }
}
