import Foundation

public enum RussianTranscriptTranslationStage: Equatable, Sendable {
    case preparingAssets
    case translatingCurrentFragment
    case translatingAhead
    case translatingRemaining
}

public enum RussianTranscriptTranslationUpdate: Equatable, Sendable {
    case stage(RussianTranscriptTranslationStage)
    case translated(cues: [CaptionCue], stage: RussianTranscriptTranslationStage)
    case telemetry(RussianTranscriptTelemetry)
}

public enum RussianTranscriptCacheHit: String, Codable, Equatable, Sendable {
    case miss
    case partial
    case full
}

public struct RussianTranscriptTelemetry: Equatable, Sendable {
    public let timeToFirstRussian: TimeInterval?
    public let translatedAheadSeconds: TimeInterval
    public let translatedCueCount: Int
    public let totalCueCount: Int
    public let cacheHit: RussianTranscriptCacheHit
    public let resumeCount: Int

    public init(
        timeToFirstRussian: TimeInterval?,
        translatedAheadSeconds: TimeInterval,
        translatedCueCount: Int,
        totalCueCount: Int,
        cacheHit: RussianTranscriptCacheHit,
        resumeCount: Int
    ) {
        self.timeToFirstRussian = timeToFirstRussian
        self.translatedAheadSeconds = max(0, translatedAheadSeconds)
        self.translatedCueCount = translatedCueCount
        self.totalCueCount = totalCueCount
        self.cacheHit = cacheHit
        self.resumeCount = resumeCount
    }
}

public enum RussianTranscriptFailure: Error, Equatable, Sendable {
    case preparationDeclinedOrOffline
    case unsupportedLanguagePair
    case translationFailed
}

public struct RussianTranscriptRequest: Equatable, Sendable {
    public let videoID: String
    public let sourceTrackID: String
    public let sourceCues: [CaptionCue]
    public let sourceLanguageCode: String
    public let sourceHash: String
    public let playbackTime: TimeInterval

    public init(
        videoID: String,
        sourceTrackID: String,
        sourceCues: [CaptionCue],
        sourceLanguageCode: String,
        sourceHash: String,
        playbackTime: TimeInterval
    ) {
        self.videoID = videoID
        self.sourceTrackID = sourceTrackID
        self.sourceCues = CaptionTranscriptPolicy.normalizedCues(sourceCues)
        self.sourceLanguageCode = sourceLanguageCode
        self.sourceHash = sourceHash
        self.playbackTime = playbackTime
    }
}

public struct RussianTranscriptResult: Equatable, Sendable {
    public let cues: [CaptionCue]
    public let wasCached: Bool

    public init(cues: [CaptionCue], wasCached: Bool) {
        self.cues = CaptionTranscriptPolicy.normalizedCues(cues)
        self.wasCached = wasCached
    }
}

@MainActor
public protocol RussianTranscriptTranslating: AnyObject {
    func translate(
        request: RussianTranscriptRequest,
        progress: @escaping @Sendable (RussianTranscriptTranslationUpdate) -> Void
    ) async throws -> RussianTranscriptResult

    func updatePriority(playbackTime: TimeInterval)
}

public enum TranscriptLanguageEvidence: Equatable, Sendable {
    case russian
    case english
    case ambiguous
}

public enum RussianTranscriptPolicy {
    public static let targetLanguageCode = "ru"
    public static let sourceEnglishLanguageCode = "en"
    public static let lookaheadSeconds: TimeInterval = 120
    public static let batchSize = 8
    public static let cacheSchemaVersion = 3

    public static func preferredSourceTrack(in tracks: [CaptionTrack]) -> CaptionTrack? {
        let russian = tracks.filter { baseLanguage($0.languageCode) == "ru" }
        if let manualRussian = russian.first(where: { !$0.isAutoGenerated }) {
            return manualRussian
        }
        if let anyRussian = russian.first { return anyRussian }

        let english = tracks.filter { baseLanguage($0.languageCode) == "en" }
        if let manualEnglish = english.first(where: { !$0.isAutoGenerated }) {
            return manualEnglish
        }
        if let anyEnglish = english.first { return anyEnglish }

        return tracks.first(where: { !$0.isAutoGenerated }) ?? tracks.first
    }

    public static func languageEvidence(in cues: [CaptionCue]) -> TranscriptLanguageEvidence {
        let sample = cues
            .prefix(240)
            .map(\.text)
            .joined(separator: " ")
        let scalars = sample.unicodeScalars
        var cyrillicLetters = 0
        var latinLetters = 0
        var totalLetters = 0

        for scalar in scalars where CharacterSet.letters.contains(scalar) {
            totalLetters += 1
            switch scalar.value {
            case 0x0400...0x052F:
                cyrillicLetters += 1
            case 0x0041...0x005A, 0x0061...0x007A:
                latinLetters += 1
            default:
                break
            }
        }

        guard totalLetters >= 80 else { return .ambiguous }
        let cyrillicShare = Double(cyrillicLetters) / Double(max(1, totalLetters))
        let latinShare = Double(latinLetters) / Double(max(1, totalLetters))
        if cyrillicLetters >= 48, cyrillicShare >= 0.55 { return .russian }
        if latinLetters >= 48, latinShare >= 0.62, cyrillicShare < 0.12 { return .english }
        return .ambiguous
    }

    public static func resolvedSourceLanguage(
        cues: [CaptionCue],
        trackLanguageCode: String
    ) -> TranscriptLanguageEvidence {
        let evidence = languageEvidence(in: cues)
        if evidence != .ambiguous { return evidence }
        switch baseLanguage(trackLanguageCode) {
        case "ru": return .russian
        case "en": return .english
        default: return .ambiguous
        }
    }

    public static func sourceHash(cues: [CaptionCue]) -> String {
        var hash: UInt64 = 14_695_981_039_346_656_037
        for cue in CaptionTranscriptPolicy.normalizedCues(cues) {
            let activation = cue.activationTime.map {
                String(Int(($0 * 1_000).rounded()))
            } ?? "source"
            let value = "\(Int((cue.startTime * 1_000).rounded()))|\(Int((cue.endTime * 1_000).rounded()))|\(activation)|\(cue.text)\n"
            for byte in value.utf8 {
                hash ^= UInt64(byte)
                hash &*= 1_099_511_628_211
            }
        }
        return String(hash, radix: 16)
    }

    public static func stableClientIdentifier(
        videoID: String,
        sourceTrackID: String,
        sourceHash: String,
        cueIndex: Int
    ) -> String {
        "\(videoID):\(sourceTrackID):\(sourceHash):\(cueIndex)"
    }

    public static func priorityOrder(
        cues: [CaptionCue],
        playbackTime: TimeInterval,
        pendingIndices: Set<Int>
    ) -> [Int] {
        guard !cues.isEmpty else { return [] }
        let time = playbackTime.isFinite ? max(0, playbackTime) : 0
        let current = CaptionTranscriptPolicy.activeCueIndex(in: cues, at: time)
            ?? cues.firstIndex(where: { $0.startTime >= time })
            ?? max(0, cues.count - 1)

        let currentRange = max(0, current - 1)...min(cues.count - 1, current + 2)
        let currentIndices = currentRange.filter { pendingIndices.contains($0) }
        let lookaheadLimit = time + lookaheadSeconds
        let lookahead = cues.indices.filter {
            pendingIndices.contains($0)
                && !currentRange.contains($0)
                && cues[$0].startTime >= time
                && cues[$0].startTime <= lookaheadLimit
        }
        let remaining = cues.indices.filter {
            pendingIndices.contains($0)
                && !currentIndices.contains($0)
                && !lookahead.contains($0)
        }
        return currentIndices + lookahead + remaining
    }

    public static func stage(
        for indices: [Int],
        cues: [CaptionCue],
        playbackTime: TimeInterval
    ) -> RussianTranscriptTranslationStage {
        guard let first = indices.first, cues.indices.contains(first) else {
            return .translatingRemaining
        }
        let time = playbackTime.isFinite ? max(0, playbackTime) : 0
        if cues[first].startTime <= time + 12 { return .translatingCurrentFragment }
        if cues[first].startTime <= time + lookaheadSeconds { return .translatingAhead }
        return .translatingRemaining
    }

    public static func translatedCues(
        source: [CaptionCue],
        translationsByIndex: [Int: String]
    ) -> [CaptionCue] {
        source.indices.compactMap { index in
            guard let translation = translationsByIndex[index]?
                .split(whereSeparator: { $0.isWhitespace })
                .joined(separator: " "),
                  !translation.isEmpty else { return nil }
            let cue = source[index]
            return CaptionCue(
                startTime: cue.startTime,
                endTime: cue.endTime,
                text: translation,
                activationTime: cue.activationTime
            )
        }
    }

    public static func translatedAheadSeconds(
        source: [CaptionCue],
        translatedIndices: Set<Int>,
        playbackTime: TimeInterval
    ) -> TimeInterval {
        guard !source.isEmpty else { return 0 }
        let time = playbackTime.isFinite ? max(0, playbackTime) : 0
        let ordered = source.indices.filter { source[$0].endTime > time }
        guard let first = ordered.first else { return 0 }
        var expected = first
        var coveredUntil = time
        for index in ordered {
            guard index == expected, translatedIndices.contains(index) else { break }
            coveredUntil = max(coveredUntil, source[index].endTime)
            expected += 1
        }
        return max(0, coveredUntil - time)
    }

    public static func responseIndex(
        clientIdentifier: String?,
        expectedIdentifiers: [String: Int]
    ) -> Int? {
        guard let clientIdentifier else { return nil }
        return expectedIdentifiers[clientIdentifier]
    }

    public static func baseLanguage(_ languageCode: String) -> String {
        languageCode
            .replacingOccurrences(of: "_", with: "-")
            .split(separator: "-")
            .first
            .map { String($0).lowercased() }
            ?? languageCode.lowercased()
    }
}

public struct RussianTranscriptWorkQueue: Equatable, Sendable {
    public let cues: [CaptionCue]
    public private(set) var pendingIndices: Set<Int>
    public private(set) var playbackTime: TimeInterval

    public init(
        cues: [CaptionCue],
        completedIndices: Set<Int> = [],
        playbackTime: TimeInterval
    ) {
        self.cues = CaptionTranscriptPolicy.normalizedCues(cues)
        self.pendingIndices = Set(self.cues.indices).subtracting(completedIndices)
        self.playbackTime = playbackTime
    }

    public var isEmpty: Bool { pendingIndices.isEmpty }

    public mutating func reprioritize(playbackTime: TimeInterval) {
        guard playbackTime.isFinite else { return }
        self.playbackTime = max(0, playbackTime)
    }

    public mutating func nextBatch(size: Int = RussianTranscriptPolicy.batchSize) -> [Int] {
        let order = RussianTranscriptPolicy.priorityOrder(
            cues: cues,
            playbackTime: playbackTime,
            pendingIndices: pendingIndices
        )
        let batch = Array(order.prefix(max(1, size)))
        pendingIndices.subtract(batch)
        return batch
    }
}
